window.tanimlarData = [
  {"t":"Acrabadin","c":"Hastalıkların ilâclarını bildiren kitâblara, (Kitâb-ül-edviye), (formüler farmasötik) ve (Acrabadin) denir.","s":652},
  {"t":"Ahkâm-ı islâmiyye","c":"Yapılması emr olunmayan ve yasak da edilmeyen şeylere (Mubâh) denir. Bu emr ve yasakların hepsine (Ahkâm-ı ilâhiyye) veyâ (Ef’âl-i mükellefîn) ve (Ahkâm-ı islâmiyye) denir.","s":18},
  {"t":"Akl","c":"Allahü teâlâ, çok merhametli olduğu için, insanda, iyi işleri kötülerinden ayıran bir kuvvet yaratdı. Bu kuvvete (Akl) denir.","s":1248},
  {"t":"Akl-ı selîm","c":"Şaşmıyan, yanılmıyan akla (Akl-ı selîm) denir.","s":530},
  {"t":"Akrabâ","c":"Analardan, baba ve dedelerden ve çocuklardan, torunlardan başka olan yakınlara, (Akrabâ) denir.","s":595},
  {"t":"Alev","c":"Gazların, buhârların yanmasına (Alev) denir.","s":548},
  {"t":"Allahü ekber","c":"Üçüncü rek’atde, zamm-ı sûre okudukdan sonra, iki el, iki yana salıverilmeden, doğruca kulaklara kaldırılarak (Allahü ekber) denir.","s":228},
  {"t":"Alâmet","c":"Yok olmazsa, (Alâmet) denir.","s":122},
  {"t":"Anyon","c":"Eksi elektrik taşıyan atomlara (Anyon) denir.","s":547},
  {"t":"Arab-ı bâide","c":"Nûh aleyhisselâmdan sonra Arabistân yarım adasında yerleşenlere (Arab-ı bâide) denir.","s":1128},
  {"t":"Arab-ı âribe","c":"Bunlardan sonra, gelip Yemene yerleşen (Kahtân) evlâdlarına (Arab-ı âribe) denir.","s":1128},
  {"t":"Artifisiel","c":"Birşeyin yaratılmasına sebeb olan şeyler arasında insan gücü de varsa, yaratılan şeye (Sun’î cism) veyâ (Artifisiel) denir.","s":433},
  {"t":"Arşullah","c":"Kâmil bir insanın kalbi, birçok bakımdan Arş gibidir. Bunun için, öyle kalbe (Arşullah) denir.","s":917},
  {"t":"Ashâr","c":"Zevcesinden, zevcinden, zî-rahm-i mahrem kadın akrabâsının kocalarından ve zevcesinin zî-rahm-i mahrem erkek akrabâsından çalarsa kesilmez. Bu sonunculara (Ashâr) denir.","s":882},
  {"t":"Atf-ı beyân","c":"Meşhûr olmıyan birincisindeki kapalılığı açıklamak için, ikincisi zikr edilir. Bu ikincisine, (Atf-ı beyân) denir.","s":389},
  {"t":"Atmosfer","c":"Hava, deniz kenârında, bir santimetre kare satha, bir kilogram tazyîk yapmakdadır. Bu basınc mikdârına, bir (Atmosfer) denir ki, yetmişaltı santimetre [76 cm] yüksekliğindeki cıvanın basıncına eşitdir.","s":980},
  {"t":"Atom","c":"Kimyâ reaksiyonlarında, maddelerin birbiri ile birleşen veyâ ayrılan en küçük parçasına (Atom) denir.","s":971},
  {"t":"Atom numarası","c":"Elementlerin devrî sistemdeki soldan sağa doğru sıra numarasına, (Atom numarası) denir.","s":549},
  {"t":"Avret mahalli","c":"58 — SETR-İ AVRET ve KADINLARIN ÖRTÜNMESİ Mükellef olan, ya’nî âkıl ve bâlig olan insanın nemâz kılarken açması veyâ her zemân başkasına göstermesi ve başkasının bakması harâm olan yerlerine (Avret mahalli) denir.","s":163},
  {"t":"Ayn","c":"olup da gösterilenin hepsine veyâ ayrılmış parçasına, mislî olan mallardan da, hâzır olup gösterilen hepsine veyâ ayrı olarak gösterilen yâhud ayrılmamış belli mikdâr bir parçasına yâhud hâzır olmayıp, benzerlerinden ayrı ve yalnız olarak bulunduğu yeri ve cinsi bildirilen mala, (Ayn) denir.","s":793},
  {"t":"Ayn-ül-yakîn","c":"Hadîs-i şerîfde bildirilen (İhsân) mertebesinden bir ışıkın kalbde parlamasına, (Ayn-ül-yakîn) denir.","s":765},
  {"t":"Azâb","c":"Allahü teâlâ insanların yapdığı işlerden bir kısmını beğenmediğini, bunları yapanlardan râzı olmadığını, fekat pişmân olup tevbe edenleri veyâ şefâ’ate kavuşanları afv edeceğini, afv edilmiyenlerin kötü işlerine kıyâmetde, çok acı karşılıklar vereceğini, Cehennem ateşinde yakacağını bildirdi. Bu acı karşılıklara, (Azâb) denir.","s":681},
  {"t":"A’zamallahü ecrek ve ahsene azâek ve gafere limeyyitik","c":"Ta’ziye için, (A’zamallahü ecrek ve ahsene azâek ve gafere limeyyitik) denir ki, (Allahü teâlâ, sevâbını, dereceni artdırsın ve güzel sabr etmeni nasîb eylesin ve meyyitinin günâhlarını afv eylesin) demekdir.","s":1006},
  {"t":"Basît cism","c":"Element: Kendisinden, başka başka özellikde maddeler çıkarılamıyan saf maddelere (Element=eleman) veyâ (Basît cism) denir.","s":546},
  {"t":"Basît cism, eleman","c":"Bir sâf cismden, başka bir madde çıkarılamaz ise, bu maddeye (Basît cism, eleman) denir.","s":971},
  {"t":"Bat satışı","c":"Vefâ ile, ikrâh ile ve muhayyerlikle olmıyan şartsız satışlara, (Bat satışı) denir.","s":814},
  {"t":"Batı Avrupa zemânı","c":"Londra şehrinin yedibuçuk derece şarkından ve garbından geçen iki tûl dâiresi arasında bulunan her yerde Londranın vasatî sâati müşterek olarak kullanılmakdadır. Buna (Batı Avrupa zemânı) denir.","s":190},
  {"t":"Bedîhî","c":"Akl ile bilmek de ikidir: Düşünmeden hemen bilinirse, (Bedîhî) denir.","s":782},
  {"t":"Behâr hattı","c":"Erdın bu kutruna (Behâr hattı) denir.","s":183},
  {"t":"Ben müslimânım. Benden sana zarar gelmez. Selâmetdesin","c":"(Selâmün aleyküm) demek, (Ben müslimânım. Benden sana zarar gelmez. Selâmetdesin) demekdir.","s":364},
  {"t":"Ben yokum, Hak teâlâ vardır","c":"Onun sözünün ma’nâsı, (Ben yokum, Hak teâlâ vardır) demekdir.","s":944},
  {"t":"Benim ictihâdıma göre sahîh olmamışdır","c":"Üsûl-i hadîs âlimleri, bir hadîsin sahîh olması için koydukları şartları taşımıyan bir hadîse (Mevdû’) der ki, (Benim ictihâdıma göre sahîh olmamışdır) demekdir.","s":1015},
  {"t":"Benim mezhebimdeki sahîh olmak şartları yokdur","c":") Süyûtî, Zehebî ve Askalânî gibi hadîs âlimleri, birkaç hadîs-i şerîfe mevdû’ demişler ise de, bu sözleri, (Benim mezhebimdeki sahîh olmak şartları yokdur) demekdir.","s":442},
  {"t":"Benî-Hâşim","c":"Resûlullahın ve amcalarının oğullarına (Hâşimî) veyâ (Benî-Hâşim) denir.","s":1108},
  {"t":"Benûl-ahyâf","c":"Anadan kardeşler: Bunlara, (Benûl-ahyâf) denir.","s":1026},
  {"t":"Bid’at sâhibi","c":"Kur’ândan ve hadîsden yanlış ma’nâ çıkarana (Bid’at sâhibi) denir.","s":16},
  {"t":"Bid’at talâk","c":"Bir def’ada üç kerre talâk vermeğe, (Bid’at talâk) denir.","s":582},
  {"t":"Bileşik cism","c":"Başka maddelere ayrılabilen sâf cisme (Bileşik cism) denir.","s":971},
  {"t":"Bilmediklerinizi, bildiklerinize kıyâs ediniz!","c":"(Ey ilm sâhibleri! İ’tibâr ediniz!) âyet-i kerîmesi, (Bilmediklerinizi, bildiklerinize kıyâs ediniz!) demekdir.","s":474},
  {"t":"Bismillâhirrahmânirrahîm","c":"Besmele okumak, (Bismillâhirrahmânirrahîm) demekdir.","s":3},
  {"t":"Biz günâhı çok, âsî kulların yaratanı, yetişdireni her aybdan münezzehdir","c":"Hâlbuki, (Sübhâne rabbinâ) demek, (Biz günâhı çok, âsî kulların yaratanı, yetişdireni her aybdan münezzehdir) demekdir.","s":394},
  {"t":"Bu şey, bu işin yapılmasına sebeb ol - du, vâsıta oldu","c":"Hâlbuki, böyle sözleri kendileri de söylemekdedir. Bu sözler (Bu şey, bu işin yapılmasına sebeb ol - du, vâsıta oldu) demekdir.","s":478},
  {"t":"Bâbürrahme","c":"Bunlardan: İkisi garb dıvarında olup, kıbleye yakın olana, (Bâbüsselâm), şimâl köşesine yakın olana, (Bâbürrahme) denir.","s":348},
  {"t":"Bâbüt-tevessül","c":"Bedr gazâsından iki ay evvel, ya’nî ikinci senenin Receb ayında, Kıblenin Kâ’be cihetine tahvîli emr olununca, kapısı cenûb dıvarından şimâl dıvarına alınırken, mescidin tûlü ve arzı yüzer zrâ’ [42 metre] yapıldı. Bu kapıya (Bâbüt-tevessül) denir.","s":348},
  {"t":"Bî’at-ür-rıdvân","c":"Muhyissünne imâm-ı Begavî “rahmetullahi teâlâ aleyh”, (Me’âlimüttenzîl) ismindeki tefsîr kitâbında, ma’nâ verirken diyor ki: Câbir bin Abdüllah “radıyallahü anh” dedi ki, Resûlullah “sallallahü aleyhi ve sellem”, (Ağaç altında benimle sözleşenlerden hiçbiri Cehenneme girmez!) buyurdu. Bu sözleşmeye, (Bî’at-ür-rıdvân) denir.","s":507},
  {"t":"Cennet","c":"Ni’metlerin verileceği yere, (Cennet) denir.","s":681},
  {"t":"Cism","c":"Maddelerin şekl almış parçalarına, (Cism) denir.","s":971},
  {"t":"Contüsion","c":"Çok acır, sızlar. Buna (Ezik) veyâ (Contüsion) denir.","s":675},
  {"t":"Câmi’","c":"Müslimânların ma’bedine (Mescid) ve (Câmi’) denir.","s":244},
  {"t":"Cünn-i leyl","c":"Geceye (Cünn-i leyl) denir.","s":735},
  {"t":"Cünüb","c":"Gusl abdesti olmıyana (Cünüb) denir.","s":122},
  {"t":"Dahk","c":"Yalnız kendi işitirse (Dahk) denir.","s":127},
  {"t":"Da’vâ açmak","c":"b) Kendinin başkasında bulunan hakkını haber vermekdir. Buna (Da’vâ açmak) denir.","s":884},
  {"t":"Dehrî","c":"Hiçbir dîne inanmayanlara (Ateist) ve (Dehrî) denir.","s":1043},
  {"t":"Devrî tasnîf","c":"Yüzbeş elementin, yedi devr ve sekiz gurup teşkîl etmek üzere sıralanmasına, (Periyodik sistem) veyâ (Devrî tasnîf) denir.","s":549},
  {"t":"Deyn","c":"Alış verişde ise, hâzır olmayıp ayrı olarak bulunduğu yeri bildirilmiyen her dürlü mala ve hâzır ise de, ayrı olarak gösterilmiyen kıyemî mal parçasına, (Deyn) denir.","s":793},
  {"t":"Dinde reformcu","c":"ci maddeye bakınız! Din bilgilerini, fen bilgilerine göre değişdiren kâfirlere (Felesof) ve (Dinde reformcu) denir.","s":1043},
  {"t":"Dirhem","c":"Altın paralara (Dînâr), gümüş paralara (Dirhem) denir.","s":802},
  {"t":"Diyânât","c":"Allah ile kul arasında olan işlere (Diyânât) denir.","s":159},
  {"t":"Dâlle","c":"Âdet zemânını unutan kadına (Muhayyire) veyâ (Dâlle) denir.","s":139},
  {"t":"Dîn-i islâm","c":"Onun yolu, Kur’ân-ı kerîmin gösterdiği yoldur. Bu yola (Dîn-i islâm) denir.","s":17},
  {"t":"Dünyâ mel’ûndur","c":"Ya’nî (Dünyâ mel’ûndur) demekdir.","s":30},
  {"t":"Dürzî","c":"İslâmiyyeti yıkmağa uğraşdı. Bunun ve talebesi Hamzanın yolunda olanlara (Derezî) veyâ (Dürzî) denir.","s":1089},
  {"t":"Ecîr","c":"Mal sâhibine (Âcir) veyâ (Mûcir), kirâcıya ve işverene, ya’nî ücreti ödeyene, (Müste’cir), kendi kuvvetini veyâ san’atini kirâya verene, ya’nî çalışan kimseye (Ecîr) denir.","s":869},
  {"t":"Edille-i şer’ıyye","c":"Fıkh bilgisinin bu dört kaynağına (Edille-i şer’ıyye) denir.","s":437},
  {"t":"Edâ","c":"Her cins nemâzı vaktinde kılmağa (Edâ) denir.","s":272},
  {"t":"Edâ etmek","c":"[Bu üç kısm ibâdeti belli zemânlarda yapmağa (Edâ etmek) denir.","s":52},
  {"t":"Efsûn","c":"Ma’nâsı bilinmiyen veyâ küfre sebeb olan rukyeyi okumağa, (Efsûn) denir.","s":784},
  {"t":"Ehl-i kitâb","c":"Bir Peygambere ve bunun, sonradan bozulmuş olan (Mukaddes kitâb)ına inanan bir kâfir, bu Peygamber tanrıdır veyâ oğludur dese ve putlara yalvarırsa da, buna (Ehl-i kitâb) denir.","s":327},
  {"t":"Ehl-i sünnet","c":"Selef-i sâlihînin “rahmetullahi teâlâ aleyhim ecma’în” yolunda bulunan müslimânlara (Ehl-i sünnet) denir.","s":408},
  {"t":"Ehl-i sünnet vel-cemâ’at mezhebi","c":"Üçüncü ve dördüncü asrlarda gelen islâm âlimlerine (Halef-i sâdıkîn) denir. Bu şerefli insanların i’tikâdına, (Ehl-i sünnet vel-cemâ’at mezhebi) denir.","s":492},
  {"t":"Ehl-i sünnet âlimi","c":"Bunlar da, kitâblarına yazdılar. Bu kitâbları yazan âlimlere (Ehl-i sünnet âlimi) denir.","s":2},
  {"t":"Elektro-manyetik dalgalar","c":"Bir telden elektrik ceryânı geçince, telin etrâfında miknâtis dalgaları hâsıl olur. Bu dalgalara (Elektro-manyetik dalgalar) denir.","s":563},
  {"t":"Elektron","c":"Elektriğin, hiç bölünmiyen en küçük parçasına (Elektron) denir.","s":971},
  {"t":"Emvâl-i bâtına","c":"Zekât mallarından altın, gümüş ve ticâret eşyâsına (Emvâl-i bâtına) denir.","s":309},
  {"t":"Emvâl-i zâhire","c":"İbni Âbidîn “rahmetullahi aleyh” buyuruyor ki: (Dört nev’ zekât malından ikisine, ya’nî zekât hayvanları ile toprakdan elde edilen mallara (Emvâl-i zâhire) denir.","s":309},
  {"t":"Emânet","c":"(Mecelle)nin yediyüzaltmışikinci (762) maddesinde diyor ki: Güvenilen kimseye bırakılan mala (Emânet) denir.","s":605},
  {"t":"En yakın şey","c":"Fen ilminde (En yakın şey) demekdir.","s":78},
  {"t":"En zararlı, fenâ şey","c":"Dünyâ kelimesinin din bilgisindeki ma’nâsı, (En zararlı, fenâ şey) demekdir.","s":78},
  {"t":"Entorse","c":"Yerinden oynar, fekat çıkmazsa (burkulma) veyâ (Entorse) denir.","s":675},
  {"t":"Erdin kutubları","c":"Bu mihver, Erdin merkezinden geçer ve Erdin sathını (yüzeyini) iki noktada delen bir doğrudur. Bu iki noktaya (Erdin kutubları) denir.","s":175},
  {"t":"Eshâb","c":"Birkaç dânesine (Eshâb) denir.","s":1046},
  {"t":"Eshâb-ı soffa","c":"Medîneli Ensârın fakîr olanları ile Muhâcirlerin fakîrleri, (Mescid-i nebî) yanındaki (Soffa) denilen büyük çardak altında yaşarlar, ilm öğrenmek ve öğretmekle uğraşırlar, ömrlerinin çoğu Resûlullah ile birlikde cihâd etmekle geçerdi. Bunlara (Eshâb-ı soffa) denirdi.","s":621},
  {"t":"Eshâb-ı yemîn","c":"Zulmânî, karanlık perdeler arkasında kalanlara, (Eshâb-ı şimâl) denir. Bu perdeleri aşıp, nûrdan perdeler gerisinde bulunanlara (Eshâb-ı yemîn) denir.","s":913},
  {"t":"Eshâb-ı şimâl","c":"Allahü teâlâ, sana doğru yolda ilerlemek nasîb eylesin! Zulmânî, karanlık perdeler arkasında kalanlara, (Eshâb-ı şimâl) denir.","s":913},
  {"t":"Eski serây","c":"Bir sene sonra Bâyezîd kulesinin olduğu yerde, ilk türk serâyını yapdırdı. Bu büyük serâya (Eski serây) denir.","s":1100},
  {"t":"Esmâ-i hüsnâ","c":"Kâdî zâde Ahmed efendi, (Birgivî vasıyyetnâmesi) şerhinde diyor ki, (Allahü teâlânın doksandokuz ismine (Esmâ-i hüsnâ) denir.","s":431},
  {"t":"Espes pektoral","c":"Müsâvî mikdârda (sığır kuyruğu, gelincik, hatmi, kedi ayağı, deve tabanı ve menekşe) çiçekleri karışımına (Espes pektoral) denir.","s":673},
  {"t":"Essalâtü câmi’a","c":"Bundan önce, nemâz vaktlerinde yalnız (Essalâtü câmi’a) denirdi.","s":204},
  {"t":"Estagfirullah","c":"Dil ile yirmibeş kerre (Estagfirullah) denir, herbirini söy- [1] (Bir kimse, bu mektûbu okuyup, seve seve yaparsa, ona izn verilmiş olur demişlerdir.","s":921},
  {"t":"Evliyâ","c":"Halâl olsun, mubâh olsun, mâ-sivâyı, ya’nî Allahü teâlâdan başka herşeyi hâtırlamağı kalbinden çıkarmağa (Fenâ-fillah) denir. Buna kavuşan müslimâna (Velî) denir, (Evliyâ) denir.","s":78},
  {"t":"Ey Bilâl! Ezân okuyarak ve nemâzın ikâmetini söyliyerek, beni râhata kavuşdur","c":"Bir hadîs-i şerîfde, (Yâ Bilâl “radıyallahü teâlâ anh”! Beni râhatlandır!) buyuruldu ki, (Ey Bilâl! Ezân okuyarak ve nemâzın ikâmetini söyliyerek, beni râhata kavuşdur) demekdir.","s":769},
  {"t":"Ey insanlar ve cinnîler!","c":"2 — Errahmân sûresi, yetmişdördüncü âyetinde, Cinnin Cennete gireceği bildiriliyor. 3 — Errahmân sûresinin otuzbirinci âyetinde (Sekalân) buyuruyor ki, (Ey insanlar ve cinnîler!) demekdir.","s":736},
  {"t":"Eyyâm-i nahr","c":"4 — KURBAN BAYRAMI GECELERİ: Kurban bayramının birinci, ikinci ve üçüncü günlerinden sonraki gecelerdir. Bu üç güne (Eyyâm-i nahr) denir.","s":352},
  {"t":"Eyyâm-ı teşrîk","c":"Kurban bayramının 2, 3 ve dördüncü üç gününe (Eyyâm-ı teşrîk) denir.","s":266},
  {"t":"Ezân-ı Cavk","c":"] (İbni Âbidîn)de ve (Ukûd-üd-dürriyye)de diyor ki, (Minârede ve Cum’a hutbesi okunacağı zemân, birkaç müezzinin birlikde ezân okumalarına (Ezân-ı Cavk) denir.","s":205},
  {"t":"E’ûzü billâhi mineşşeytânirracîm","c":"E’ûzü okumak, (E’ûzü billâhi mineşşeytânirracîm) demekdir.","s":3},
  {"t":"Fadl-ı dâir=Zemân farkı","c":"Güneşin [merkezinin] meyli bilinen bir gündeki ve arz derecesi bilinen bir mahaldeki mahreki üzerinde, hakîkî üfka nazaran nemâzın irtifâ’ına ulaşdığı hakîkî vaktinin, zevâlden veyâ gece yarısından farkını bildiren hakîkî güneş zemânı hesâb edilir. Bu zemâna (Fadl-ı dâir=Zemân farkı) denir.","s":187},
  {"t":"Fakîh","c":"Fıkh bilgilerini bilen kimseye (Fakîh) denir.","s":437},
  {"t":"Farz","c":"(Redd-ül-muhtâr)da vitr nemâzını anlatırken diyor ki, (İnanması da, yapması da farz olan emrlere (Farz) denir.","s":230},
  {"t":"Felsefe","c":"Tecribeye, hesâba dayanmıyan şahsî düşüncelere (Felsefe) denirdi.","s":409},
  {"t":"Fen yobazı","c":"eketleri, yüksek tahsîl ismini lekelemez mi? Alçak görgülü olan bile, bu kadar câhilce konuşur mu? Fen adamlarının tecribelerini, sözlerini işitip de, kendi kurdukları yalanları, plânları, bu sözlerle maskeleyerek, gençleri zehrlemeğe, îmânlarını çalmağa uğraşan din hırsızlarına (Fen yobazı) denir.","s":542},
  {"t":"Fenâ makâmı","c":"Çünki, aynanın gayb olması lâzımdır. Bu hâle, (Fenâ makâmı) denir ve çok kıymetlidir.","s":912},
  {"t":"Fenâ-fillah","c":"Halâl olsun, mubâh olsun, mâ-sivâyı, ya’nî Allahü teâlâdan başka herşeyi hâtırlamağı kalbinden çıkarmağa (Fenâ-fillah) denir.","s":78},
  {"t":"Fenâ-yi kalb","c":"Hakîkî sevgi pekçok olursa, sevdiğinden başka herşeyi unutur. Bu unutmağa (Fenâ-yi kalb) denir.","s":1056},
  {"t":"Fenâ-yi nefs","c":"Kendini de unutmağa (Fenâ-yi nefs) denir.","s":1056},
  {"t":"Ferâg etmek","c":"(Ferâg etmek) denir.","s":813},
  {"t":"Fey","c":"Muhârebe bitdikden sonra kâfirlerden zorla alınan mâla (Fey) denir.","s":577},
  {"t":"Fey-i zevâl","c":"En kısa gölge uzunluğuna (Fey-i zevâl) denir.","s":182},
  {"t":"Feyz","c":"Ültra viyole ışınlar, ciğerleri temizlediği gibi, kalb aynasını temizleyen, kalbi hastalıkdan kurtaran şuâ’lar da vardır. Bu şuâ’lara (Nûr), (Feyz) denir.","s":1049},
  {"t":"Fi - râset","c":"3 — Ümmet arasında, Velî olmıyanlardan meydâna gelen âdet dışı şeylere, (Fi - râset) denir.","s":748},
  {"t":"Fibrin","c":"Kesilen yerden çıkan kandaki fibrinogen, iplikler hâlinde pıhtılaşır. Bu pıhtıya (Fibrin) denir.","s":977},
  {"t":"Fiyâtı","c":"(Bâyı’) ile (Müşterî) arasında uyuşulan değerine, (Pazarlık semeni) veyâ (Alış Semeni) veyâ (Fiyâtı) denir.","s":795},
  {"t":"Frekans=te - kerrür","c":"Bir sâniyedeki dalga adedine (Frekans=te - kerrür) denir.","s":548},
  {"t":"Fudûl","c":"Mubâhların fazlasına (Fudûl) denir.","s":428},
  {"t":"Fâsid kan","c":"Üç günden, ya’nî yetmişiki sâatden, beş dakîka bile az olan ve yeni başlıyan için on günden çok sürünce, onuncu günden sonra ve yeni olmıyanlarda âdetden çok olup, on günü de aşınca, âdetden sonraki günlerde gelmiş olan ve hâmile ve âyise [ihtiyâr] kadınlardan ve dokuz yaşından küçük kızlardan gelen kanlar, hayz olmaz. Buna (İstihâza) veyâ (Fâsid kan) denir.","s":137},
  {"t":"Fâsid temizlik","c":"Onbeş veyâ dahâ ziyâde temiz gün içinde fâsid kan ya’nî istihâza kanı bulunursa, bu günlerin hepsine (Hükmî temizlik) veyâ (Fâsid temizlik) denir.","s":136},
  {"t":"Fülûs","c":"[Altından ve gümüşden başka ma’denlerden basılmış paralara, (Fülûs) denir.","s":796},
  {"t":"Fıkh ilmi","c":"Zarûrî bilgilerden birincisine (Kelâm ilmi), ikincisine (Fıkh ilmi) denir.","s":480},
  {"t":"Fısk meclisi","c":"Avret mahalli açık olan kimselerin bulunduğu yere veyâ harâm işlenen her yere (Fısk meclisi) denir.","s":169},
  {"t":"Gaben-i fâhiş=çok aldanmak","c":"(Mecelle)nin yüzaltmışbeşinci [165] maddesinde diyor ki, sarraflıkda piyasadaki fiyâtların en yükseğinden, yüzde ikibuçuk [% 2,5] ve dahâ fazlası kadar yüksek fiyâtla satın alarak aldanmağa (Gaben-i fâhiş=çok aldanmak) denir.","s":807},
  {"t":"Gaben-i yesîr=az aldanmak","c":"dâr, urûz için, ya’nî hayvândan başka menkûl mallar için yüzde beş, hayvân için yüzde on, binâ için yüzde yirmidir. Bu mikdârlardan az olan aldanmağa, (Gaben-i yesîr=az aldanmak) denir.","s":808},
  {"t":"Gadab","c":"İkincisi, yaşamalarına zarârlı olan, canlarını yakan şeylerden kaçmak, bunlara karşı savunmak kuvvetidir. Bu kuvvete, (Gadab) denir.","s":529},
  {"t":"Ganîmet","c":"Harbde kâfirlerden zorla alınan mala, (Ganîmet) denir.","s":577},
  {"t":"Gasb etmek","c":"(Hadîka)da el âfetlerinde diyor ki, (Başkasının malını ondan iznsiz, zorla almağa, (Gasb etmek) denir.","s":536},
  {"t":"Gayb","c":"Görülüyor ki, islâm dîninin, hesâbın ve tecribenin bildirmediği şeylere (Gayb) denir.","s":782},
  {"t":"Geçici vatan","c":"Giriş ve çıkış günlerinden başka hanefîde onbeş, şâfi’î ve mâlikîde dört gün veyâ çok devâmlı kalıp, sonra çıkmağa niyyet edilen yere (Geçici vatan) denir.","s":225},
  {"t":"Gurup","c":"Bunlara, yukardan aşağı, bir (Gurup) denir.","s":549},
  {"t":"Gâye-i irtifâ’ı","c":"Üfkdan i’tibâren en yüksek olduğu vakt (zevâl vakti)dir. Bu vakt, güneşin (üfk-ı zâhirî hattından) olan yüksekliğine, güneşin (Gâye-i irtifâ’ı) denir.","s":175},
  {"t":"Güneşin meyli","c":"Güneşin merkezi ile Ekvator sathı arasında kalan meyl dâiresi kavsinin derecesine (Güneşin meyli) denir.","s":177},
  {"t":"Günâh","c":"Azâbların şiddetlerini, çokluğunu bildiren ölçü birimine, (İsm) ve (Günâh) denir.","s":681},
  {"t":"Günâhkâr","c":"Böyle kimselere (Âsî) ve (Fâsık) [kötü kimse] denir ve (Günâhkâr) denir.","s":30},
  {"t":"Haberci","c":"Bir kimsenin sözünü başkasına götürene (Resûl) veyâ (Haberci) denir.","s":834},
  {"t":"Hacc-ı asgar","c":"Umreye (Hacc-ı asgar) denir.","s":339},
  {"t":"Haccetül-İslâm","c":"Farz olan hacca (Hacc-ı ekber) veyâ (Haccetül-İslâm) denir.","s":339},
  {"t":"Hadîs müctehidi","c":"Üçyüzbinden dahâ çok hadîs-i şerîfi, râvîleri ile, senedleri ile birlikde ezber bilene (Hadîs imâmı) ve (Hadîs müctehidi) denir.","s":423},
  {"t":"Hadîs-i kudsî","c":"[Kelimeleri Peygamberimizden “sallallahü aleyhi ve sellem”, ma’nâları, Allahü teâlâdan olan hadîs-i şerîflere, (Hadîs-i kudsî) denir.","s":915},
  {"t":"Hadîs-i şerîf","c":"Muhammed aleyhisselâmın sözlerine (Hadîs-i şerîf) denir.","s":1043},
  {"t":"Hafaza melekleri","c":"İnsanların iki omuzunda bulunup, iyiliklerini ve kötülüklerini yazan (Kirâmen kâtibîn) ismindeki iki melek ile, cinnîlerden koruyan meleklere, (Hafaza melekleri) denir.","s":240},
  {"t":"Hakîkat","c":"Bu makâmda, kalb yalnız Allahü teâlâyı hâtırlamakdadır. Bu makâma (Bekâ) makâmı ve (Hakîkat) denir.","s":949},
  {"t":"Hakîkî gurûb","c":"Üç nev’i gurûb vardır: Şemsin merkezinin hakîkî irtifâ’ının sıfır olduğu vakte (Hakîkî gurûb) denir.","s":186},
  {"t":"Hakîkî gün","c":"Yine, zevâl vaktinde kol sâatimiz 12 iken başlıyarak, ertesi gün zevâl vaktine kadar geçen zemâna bir (Hakîkî gün) denir.","s":188},
  {"t":"Hakîkî güneş günü","c":"Güneş merkezinin, Nısf-ün-nehârdan iki geçişi, ya’nî iki hakîkî zevâl vakti arasındaki zemâna (Hakîkî güneş günü) denir.","s":183},
  {"t":"Hakîkî güneş sâati","c":"Hakîkî güneş gününün 24 de birine bir (Hakîkî güneş sâati) denir.","s":184},
  {"t":"Hakîkî irtifâ’ kavsi","c":"Güneşin merkezinden geçen semt dâiresinin, bu mahallin hakîkî üfkunu kesdiği semâdaki N noktası ile güneşin merkezi arasındaki GN kavs [yay] parçasına (Hakîkî irtifâ’ kavsi) denir.","s":177},
  {"t":"Hakîkî zevâl mahalli","c":"Râsıd en aşağı noktada iken, bütün üfuklara ve zâhirî üfuk hattına nazaran, zevâl mahalleri aynı bir noktadır ve güneşin günlük mahrekinin gündüz kısmının, nısf-ün-nehâr dâiresini kestiği nokta, 185.ci sahîfedeki şeklde gösterilen A noktası olup, mahrekin gündüz kısmının ortasıdır. Bu noktaya (Hakîkî zevâl mahalli) denir.","s":181},
  {"t":"Halef-i sâdıkîn","c":"Bunlardan sonra, hicretin dörtyüz senesi sonuna kadar gelen Ehl-i sünnet âlimlerine, (Halef-i sâdıkîn) denir.","s":1051},
  {"t":"Halk","c":"İlk ikisine (Kesb), son ikisine (Halk) denir.","s":702},
  {"t":"Halâl","c":"Yasak edilmiş olmıyan, yâhud yasak edilmiş ise de, islâmiyyetin özr, mâni’ ve mecbûriyyet tanıdığı sebeblerden birisi ile yasaklığı kaldırılmış olan şeylere (Halâl) denir.","s":18},
  {"t":"Halîfe","c":"Bir islâm devletinin reîsine (Halîfe) denir.","s":1138},
  {"t":"Halîtan","c":"Buna, (Halîtan) denir.","s":625},
  {"t":"Harac","c":"Bir farzın yapılmasına mâni’ veyâ harâm işlemeğe sebeb olanı önlemenin meşakkatli, güç olmasına (Harac) denir.","s":135},
  {"t":"Hareket-i hakîkiyye","c":"Ya’nî, masa üstüne konan bir Erd küresine yukarıdan bakınca, şimâl memleketlerinde, sâat ibreleri hareketinin ters cihetine doğru dönmekdedir. Buna (Hareket-i hakîkiyye) denir.","s":183},
  {"t":"Hareket-i ric’ıyye","c":"Güneşin ve sâbit yıldızların, şarkdan garba doğru, Erd küresi etrâfında hergün bir devr yapdıkları görülür. Buna (Hareket-i ric’ıyye) denir.","s":183},
  {"t":"Harem-i şerîf","c":"Mescid-i harâma (Harem-i Kâ’be) veyâ (Harem-i şerîf) denir.","s":343},
  {"t":"Haremeyn-i şerîfeyn","c":"Mekke ve Medîne şehrlerine (Haremeyn-i şerîfeyn) denir.","s":343},
  {"t":"Harâm","c":"Allahü teâlânın emrlerine (Farz), yasak etdiği şeylere (Harâm) denir.","s":98},
  {"t":"Hatîm","c":"Yerde bu oluk hizâsında kavs şeklindeki dıvarcık ile Kâ’be-i mu’azzama arasında kalan yere (Hatîm) denir.","s":348},
  {"t":"Havra","c":"Yehûdîlerin ma’bedlerine (Sinagog) ve (Havra) denir.","s":244},
  {"t":"Havârî","c":"Kendisinden sonra Îsevîliği dünyâya yaymak için, Eshâbı arasından seçdiği oniki mü’mine (Havârî) denir.","s":1108},
  {"t":"Hayz kanı","c":"(Seyf-ül-ebrâr) kitâbına bakınız! [Mâlikî mezhebinde, dokuz yaşına gelmiş kızın önünden, bir sebeb olmadan akan kırmızı, sarı veyâ bulanık kana (Hayz kanı) denir.","s":889},
  {"t":"Hek","c":"Meselâ, (Sünen-i Dâre Kutnî) (KTın) ve (Sünen-i kebîr-i Beyhekî) (Hek) denir].","s":424},
  {"t":"Herşey Ondandır","c":"Bundan anlaşıldı ki, sôfiyye, eşyâya, Hak teâlâdan meydâna gelmişdir, Hak teâlâ değildir diyor. O hâlde, sôfiyyenin (Herşey Odur) sözleri, (Herşey Ondandır) demekdir ki, âlimler de böyle söylemekdedir.","s":944},
  {"t":"Hicret","c":"Târîhcilere göre mîlâdın 622 senesinde, Allahü teâlânın emri ile, Mekkeden Medîneye gitdi. Bu yolculuğuna (Hicret) denir.","s":1139},
  {"t":"Hil","c":"(Mîkât) denilen yerler ile, Harem-i Mekke arasına (Hil) denir.","s":343},
  {"t":"Hisbet","c":"El ile yapmağa (İhtisâb) ve (Hisbet) denir.","s":885},
  {"t":"Hisse-i fecr","c":"(Rub’-ı dâire) ta’rifesine bakınız! Fecr vakti ile tulû’ vakti arasındaki zemâna (Hisse-i fecr) denir.","s":198},
  {"t":"Hisse-i şafak","c":"Şafak vakti ile gurûb vakti arasındaki zemâna (Hisse-i şafak) denir.","s":198},
  {"t":"Hisse-i şâyı’a sâhibi","c":"Madde 1013 — Bir binâya ortak olarak mâlik olan kimselere, (Hisse-i şâyı’a sâhibi) denir.","s":818},
  {"t":"Huccet-ül-islâm","c":"Üçyüzbin ezberliyene, (Huccet-ül-islâm) denir.","s":423},
  {"t":"Hudûr","c":"Allahü teâlâ ile olmağa, (Hudûr) denir ki, hadîs-i şerîfde bildirilen (İhsân) mertebesidir.","s":768},
  {"t":"Hukemâ","c":"Din bilgilerini, fen bilgileri ile isbât eden mü’minlere (Hukemâ) denir.","s":1043},
  {"t":"Hurûf-i cümmel","c":"(Ebced hevvez huttî) kelimelerindeki harflere (Hurûf-i cümmel) denir.","s":359},
  {"t":"Hâdise, olay","c":"Cismlerde meydâna gelen değişmelere, (Hâdise, olay) denir.","s":971},
  {"t":"Hâfız","c":"Yüzbin hadîs-i şerîfi râvîleri ile birlikde, ezber bilene (Hâfız) denir.","s":1113},
  {"t":"Hâricî","c":"Kendileri gibi inanmıyanlara kâfir dediler. Bunlara (Hâricî) denir.","s":472},
  {"t":"Hârizm","c":"İki göl arasının cenûb kısmına (Hârizm) denir.","s":431},
  {"t":"Hâs","c":"Askerin toprağına (Timar), subay toprağına (Ze’âmet), general toprağına (Hâs) denirdi.","s":305},
  {"t":"Hîle-i şer’ıyye","c":"Böyle, farzı yapmamakdan veyâ harâm işlemekden kurtuluş yolu aramağa (Hîle-i şer’ıyye) denir.","s":859},
  {"t":"Iyâl","c":"Kendilerine nafaka verilmesi vâcib olanlara (Iyâl) denir.","s":789},
  {"t":"Işıma","c":"Böyle zıyâ yaymağa (Şuâ’lanma) veyâ (Işıma) denir.","s":548},
  {"t":"Kabûl","c":"İkincisinin sözüne, (Kabûl) denir.","s":792},
  {"t":"Kabûl et","c":"(Âmîn), (Kabûl et) demekdir.","s":215},
  {"t":"Kader","c":"Bunlar, birbirleri ile hiç karışmaz. Bu ayırmağa, (Kazâ) ve (Kader) denir.","s":697},
  {"t":"Kalb-i hakîkî","c":"Burada bulunan nûrdan kuvvete, (Kalb-i hakîkî) denir.","s":922},
  {"t":"Kalb-i sanevberî","c":"Buna, (Kalb-i sanevberî) denir.","s":922},
  {"t":"Kalender","c":"Bunlara, (Kalender) denir.","s":486},
  {"t":"Kansızlık","c":"Hâlsizlik, baş ağrısı, kulak çınlaması, kalb çarpıntısı, el, ayak soğuması olur. Bu hâle anemi (Kansızlık) denir.","s":977},
  {"t":"Karz-ı hasen","c":"Çarşıda misli, ya’nî benzeri bulunan herşeyi, belirsiz bir zemân sonra, misli geri verilmek üzere vermeğe, (Karz-ı hasen) denir.","s":824},
  {"t":"Katod şuâ’ları","c":"Bunlara, (Katod şuâ’ları) denir.","s":549},
  {"t":"Katyon","c":"Artı elektrik taşıyan atomlara (Katyon) denir.","s":547},
  {"t":"Kazâ","c":"vaktinden sonra kılmağa (Kazâ) denir.","s":273},
  {"t":"Kazâ etmek","c":"Zemânında yapmayıp, zemân geçdikden sonra yapmağa (Kazâ etmek) denir.","s":52},
  {"t":"Kefîr","c":"Birincisine (Kumis) [kımız], diğer ikisine (Kefîr) denir.","s":625},
  {"t":"Kelime-i temcîd","c":"Buna, (Kelime-i temcîd) denir.","s":741},
  {"t":"Kendi mülkünde olanı kullanmak","c":"Allahü teâlâya, bu ma’nâda âdil denilemiyeceği gibi, böyle adâlete mecbûr da değildir. 2 — Adâletin yüksek ta’rîfi, (Kendi mülkünde olanı kullanmak) demekdir.","s":403},
  {"t":"Kerâhet zemânı","c":"NEMÂZ KILMASI TAHRÎMEN MEKRÛH, YA’NÎ HARÂM OLAN ZEMÂN ÜÇDÜR: Bu üç vakte, (Kerâhet zemânı) denir.","s":201},
  {"t":"Kerâmet","c":"Peygamberlerin “salevâtullahi teâlâ aleyhim ecma’în” mu’cize göstermesi lâzımdır. 2 — Peygamberlerin “aleyhimüsselâm” ümmetlerinin Evliyâsında, nefslerinin kötülükleri kalmadığı için âdet dışı meydâna gelen şeylere, (Kerâmet) denir.","s":747},
  {"t":"Kesb","c":"Kalbin, iyiden, kötüden birini ihtiyâr ve irâde etmesine (Kesb) denir.","s":32},
  {"t":"Kinâye","c":"Böyle, birkaç ma’nâda kullanılan kelimelere, (Kinâye) denir.","s":580},
  {"t":"Kirâ, üc - ret","c":"Îcâb ve kabûl ile yapılır. Bu satışın semenine (Kirâ, üc - ret) denir.","s":869},
  {"t":"Komünizm","c":"İhtilâlci sosyalizme (Komünizm) denir.","s":523},
  {"t":"Kurbet","c":"Bir kimse Allahü teâlâ için yapdığını bilerek tâ’at yaparsa, buna (Kurbet) denir.","s":19},
  {"t":"Kureyşî","c":"İsmi Kureyşdir. Bunun soyundan olanlara (Kureyşî) denir.","s":1101},
  {"t":"Kuru üzüm nakî’i","c":"Kuru üzüm, soğuk suda bırakılınca, şe - keri suya geçer. Bu suya, (Kuru üzüm nakî’i) denir.","s":624},
  {"t":"Kutb-i medâr","c":"Bunlara, (Kutb-i medâr) denir.","s":486},
  {"t":"Kuvvet","c":"Duran bir cismi harekete getiren, hareketde olan bir cismi durduran veyâ hareketini değişdiren sebebe (Kuvvet) denir.","s":1041},
  {"t":"Kvant","c":"Şuâ’ enerjisinin, bölünemiyen en küçük parçasına (Kvant) denir.","s":548},
  {"t":"Kâfir","c":"Fekat, Kur’ân-ı kerîmde ve hadîs-i şerîflerde açıkca bildirilen ve müslimânların asrlar boyunca inandığı bir şeye uymıyan söz ve işde bulunan bir kimse, bütün ömrünce nemâz kılsa, her ibâdeti yapsa da, buna (Kâfir) denir.","s":252},
  {"t":"Kâri’","c":"Kur’ân-ı kerîmi ezberliyene hâfız denmez, (Kâri’) denir.","s":423},
  {"t":"Kübrâ","c":"Mantık ilminde, birincisine (Sugrâ), ikincisine (Kübrâ) denir.","s":759},
  {"t":"Küfr","c":"Onun sözlerinden birine bile inanmamağa veyâ iyi ve doğru olduğunda şübhe etmeğe (Küfr) denir.","s":17},
  {"t":"Küfr-i cehlî","c":"Bilmiyerek söylemeğe (Küfr-i cehlî) denir.","s":436},
  {"t":"Küfr-i hükmî","c":"lanmak küfr olur. Buna (Küfr-i hükmî) denir.","s":53},
  {"t":"Küfr-i inâdî","c":"(Mürted) olur. Buna (Küfr-i inâdî) denir.","s":436},
  {"t":"Kütüb-i sitte","c":"Doğru oldukları, bütün islâm âlimleri tarafından tasdîk edilmiş olan hadîs kitâblarından altı dânesi, bütün dünyâda şöhret bulmuşdur. Bu altı kitâba (Kütüb-i sitte) denir.","s":423},
  {"t":"Kıble açısı","c":"Güneş bu hat üzerine gelince, (Kıble sâati) olur. Bu hat ile bu şehrden geçen tûl dâiresi arasındaki zâviyeye (Kıble açısı) denir.","s":170},
  {"t":"Kıble hattı","c":"Harîta üzerinde bir şehr ile, Mekke şehri arasında çizilen doğruya (Kıble hattı) denir.","s":170},
  {"t":"Kıble zâviyesi","c":"İstanbulun kıble istikâmeti, cenûbdan yirmidokuz derecelik bir zâviye [açı] kadar şarkdadır. Bu açıya (Kıble zâviyesi) denir.","s":170},
  {"t":"Kırâet-i şâzze","c":"(Rıyâd-ün-nâsıhîn)de diyor ki: Arabî gramer şartlarına uyan ve ma’nâyı değişdirmiyen, fekat ba’zı kelimeleri Osmân radıyallahü anhın topladığına benzemiyen Kur’ân-ı kerîme (Kırâet-i şâzze) denir.","s":47},
  {"t":"Kıyâs-ı fükahâ","c":"Kur’ân-ı kerîmden veyâ hadîs-i şerîflerden veyâ icmâ’-ı ümmetden çıkarılan ahkâm-ı islâmiyyeye (Kıyâs-ı fükahâ) denir.","s":437},
  {"t":"Lenfatik lösemi","c":"Lenfosit artması dahâ çok ise (Lenfatik lösemi) denir.","s":977},
  {"t":"Lipotropik","c":"Karaciğerde yağ toplanmasını azaltan ve yağları ciğerden çıkaran maddelere (Lipotropik) denir.","s":654},
  {"t":"Livâta","c":"Puştluk, ya’nî cinsî sapıklık denilen oğlan kirletmek dahâ büyük günâhdır. Buna (Livâta) denir.","s":140},
  {"t":"Luxation","c":"Fransızcada, (Luxation) denir.","s":675},
  {"t":"Madde","c":"Fen dersleri bildiriyor ki, ağırlığı ve hacmi olan varlıklara (Madde) denir.","s":1041},
  {"t":"Mahlûkları, hâdiseleri görmek, inceleyip anlamak ve deneyip benzerini yapmak","c":"Fen (Mahlûkları, hâdiseleri görmek, inceleyip anlamak ve deneyip benzerini yapmak) demekdir ki, bu üçünü de, Kur’ân-ı kerîm emr etmekdedir.","s":1045},
  {"t":"Malt","c":"Arpalar kurutulup un yapılır. Bu una, (Malt) denir.","s":625},
  {"t":"Maraz-ı mevt","c":"Burada, (Rûh-ul Mecelle)nin ilgili maddelerini yazacağız: Madde 1595 — Bir sene içinde ölüme sebeb olan hastalığa, (Maraz-ı mevt) denir.","s":816},
  {"t":"Mazmaza","c":"3 — Ağzı, ayrı ayrı su ile, üç kerre yıkamak. Buna (Mazmaza) denir.","s":122},
  {"t":"Ma’rifet","c":"Birincilere, (Îmân bilgileri) ve (Fıkh bilgileri) veyâ (Ahkâm-ı islâmiyye), ikincilere (Tesavvuf bilgileri) veyâ (Ma’rifet) denir.","s":25},
  {"t":"Mehr-i mu’accel","c":"Buna, (Mehr-i mu’accel) denir.","s":568},
  {"t":"Mehr-i müeccel","c":"Buna, (Mehr-i müeccel) denir.","s":568},
  {"t":"Mekrûh","c":"Onun beğenmediği şeylere ve ibâdetin sevâbını gideren şeylere (Mekrûh) denir.","s":18},
  {"t":"Menâsik","c":"İslâmiyyetde, belli bir yeri, belli bir zemânda, belli şeyleri yaparak ziyâret etmek demekdir. Bu belli şeylere (Menâsik) denir.","s":339},
  {"t":"Mer’î vakt","c":"Güneşin bir mer’î vakte geldiği, bu riyâdî vaktden 8 dakîka 20 sâniye sonra görülür ki, buna (Mer’î vakt) denir.","s":176},
  {"t":"Mesbûk","c":"İmâm bir rüknü bitirdikden sonra, bu rükne başlıyanın nemâzı kabûl olur. 25 — İmâma birinci rek’atde yetişemiyen kimseye (Mesbûk) denir.","s":233},
  {"t":"Meskûkât","c":"(Mir’ât-ül-haremeyn)in Mekke kısmında diyor ki, (Belli ağırlıkda basılmış olan altın ve gümüş paralara, (Meskûkât) denir.","s":802},
  {"t":"Mesânîd","c":"Meşhûr ve çok kıymetli hadîs kitâblarından, imâm-ı Ahmed bin Hanbelin (Müsned)i (HD) ve Ebû Ya’lâ (Müsned)i (Ya’lâ) ve Abdüllah Dârimînin (Müsned)i (DR) ve Ahmed Bezzârın (Müsned)i (Z) ile gösterilir. Bu kitâblara (Mesânîd) denir.","s":424},
  {"t":"Meyl dâireleri","c":"İki kutubdan geçen düzlemlere (Meyl düzlemleri) denir. Bu düzlemlerin semâ küresinde hâsıl etdikleri dâirelere (Meyl dâireleri) denir.","s":177},
  {"t":"Meyl düzlemleri","c":"İki kutubdan geçen düzlemlere (Meyl düzlemleri) denir.","s":177},
  {"t":"Mezheb","c":"[Bir müctehidin çıkardığı ahkâmın hepsine (Mezheb) denir.","s":49},
  {"t":"Mezhebsiz","c":"Bid’at sâhiblerine ve mülhidlere ve bunların yolunda olan câhil taklîdcilere (Mezhebsiz) denir.","s":473},
  {"t":"Mikyâs","c":"dır ki, tam dik olsun! Bu dik çubuğa (Mikyâs) denir.","s":182},
  {"t":"Miyole lösemi","c":"Lökosit artması fazla ise, (Miyole lösemi) denir.","s":977},
  {"t":"Mizmâr","c":"Lugat kitâblarında, meselâ (Müncid)de diyor ki, (Ses çıkaran âletlere (Mizmâr) denir).","s":70},
  {"t":"Mi’râc","c":"Elliiki yaşında iken, bir gece Mekkeden Kudüse ve oradan göklere götürülüp getirildi. Bu yolculuğuna (Mi’râc) denir.","s":1139},
  {"t":"Molekül şebekesi","c":"Bunlara, (Molekül şebekesi) denir.","s":547},
  {"t":"Mubâh","c":"Yapılması emr olunmayan ve yasak da edilmeyen şeylere (Mubâh) denir.","s":18},
  {"t":"Mudmerât","c":"(Kudûrî muhtasarı)nı şerh edenlerdendir. Bu şerhıne (Câmi’ul-mudmerât) veyâ kısaca (Mudmerât) denir.","s":1192},
  {"t":"Mudârib","c":"İş yapanlara, (Mudârib) denir.","s":867},
  {"t":"Muhak","c":"Ayı göremiyoruz. Bu zemâna (Muhak) denir.","s":360},
  {"t":"Muhayyer olmak","c":"5 — ALIŞ VERİŞDE MUHAYYERLİK Bâyı’ veyâ müşterînin, alış verişden vaz geçebilmek hakkına, (Muhayyer olmak) denir.","s":806},
  {"t":"Muhaşşî","c":"Hâşiyeyi yazana (Muhaşşî) denir.","s":1208},
  {"t":"Muhdis","c":"Abdesti olmıyana (Muhdis) denir.","s":122},
  {"t":"Muhlas","c":"Devâmlı ihlâs sâhiblerine (Muhlas) denir.","s":1049},
  {"t":"Muhlis","c":"Zahmet çekerek elde edilen, devâmsız ihlâsın sâhiblerine (Muhlis) denir.","s":1049},
  {"t":"Mukallid","c":"Müctehid olmıyan müslimâna, (Mukallid) denir.","s":586},
  {"t":"Mukayyed su","c":"Bunlar ile abdest ve gusl alınmaz. Bunlara (Mukayyed su) denir.","s":160},
  {"t":"Mu’addilün-nehâr dâiresi=Ekvator","c":"Erdın merkezinden geçen ve mihverine amûd olan sonsuz bir düzleme (Mu’addilün-nehâr=Ekvator düzlemi) denir. Bu ekvator sathının, Erd küresini kesdiği dâireye (Mu’addilün-nehâr dâiresi=Ekvator) denir.","s":177},
  {"t":"Mu’addilün-nehâr=Ekvator düzlemi","c":"Erdın merkezinden geçen ve mihverine amûd olan sonsuz bir düzleme (Mu’addilün-nehâr=Ekvator düzlemi) denir.","s":177},
  {"t":"Mu’cize","c":"Bunun için, Evliyâda ve papaslarda Hârikul’âde işler hâsıl olur.] 1 — Peygamberlerden “aleyhimüsselâm”, tam temiz oldukları için âdet-i ilâhiyye dışında ve kudret-i ilâhiyye içinde şeyler meydâna gelir. Buna (Mu’cize) denir.","s":747},
  {"t":"Mu’âmelât","c":"(Dürr-ül-muhtâr) beşinci cildde, altın ve gümüş kullanmağı anlatırken diyor ki, insanların birbirleri arasında olan işlere (Mu’âmelât) denir.","s":159},
  {"t":"Mâ-verâ-ün-nehr","c":"İki nehr arasına (Mâ-verâ-ün-nehr) denir.","s":431},
  {"t":"Müctehid","c":"Bunu ancak Peygamberimiz “sallallahü aleyhi ve sellem” ve Onun Eshâbının hepsi ve diğer müslimânlardan ictihâd makâmına yükselenler yapabilir ki, bu çok yüksek insanlara, (Müctehid) denir.","s":50},
  {"t":"Müdelles","c":"Başdan yalnız birinci râvîsi bildirilmiyen hadîse (Müdelles) denir.","s":422},
  {"t":"Müdâhene","c":"Dünyâlık ele geçirmek için dîni vermeğe (Müdâhene) denir.","s":398},
  {"t":"Müdârâ","c":"Gücü yetdiği hâlde, fitne çıkarmamak için nasîhat etmezse, (Müdârâ) denir, câiz olur.","s":398},
  {"t":"Müekked sünnet","c":"Bunları devâmlı yaparak, nâdiren terk etmiş ve terk edenlere birşey dememiş ise, (Sünnet-i hüdâ) veyâ (Müekked sünnet) denir.","s":52},
  {"t":"Müfsidleri","c":"67 — NEMÂZI BOZAN ŞEYLER Aşağıdaki yazılar, (Dürr-ül-muhtâr)dan terceme edilmişdir: Nemâzı bozan şeylere, (Müfsidleri) denir.","s":231},
  {"t":"Mühâyee","c":"Müşterek bir ayn [mal] bâkî kalmak üzere, bunun menfe’atini taksîm etmeğe (Mühâyee) denir.","s":823},
  {"t":"Mükellef","c":"55 — ÖLÜM, ÖLÜME HÂZIRLANMAK Aşağıdaki bilgiler, seyyid Abdülhakîm bin Mustafâ efendi “rahmetullahi aleyh”in (Sefer-i âhıret) risâlesinden alınmışdır. Bu risâle basılmamışdır: Îmânı olan ve aklı olan ve bâliğ olan erkek ve kadınlara, (Mükellef) denir.","s":988},
  {"t":"Müleffık","c":"Abdülganî Nablüsî hazretleri “rahmetullahi teâlâ aleyh”, (Hadîka) kitâbının ikiyüzyedinci [207] sahîfesinde buyuruyor ki, (Mezheblerin ruhsatlarını, ya’nî kolaylıklarını araşdırarak, işini bunlara uygun olarak yapan kimseye (Müleffık) denir.","s":843},
  {"t":"Mülhid","c":"yüzdoksanaltıncı ve üçyüzdokuzuncu sahîfelerinde diyor ki, (Ma’nâları açık ve kat’î olan âyet-i kerîmelere ve hadîs-i şerîflere, te’vîl etse dahî, yanlış ma’nâ vererek ve ma’nâları açıkca anlaşılmıyanları te’vîl etmeden yanlış ma’nâ vererek dinden çıkana, ya’nî îmânı bozuk olana (Mülhid) denir.","s":463},
  {"t":"Mülk-i habîs","c":"Harâmdan topladığı malları, kendi halâl malı ile, yâhud birbirleri ile karışdırsa, (Mülk-i habîs) denir.","s":611},
  {"t":"Münker","c":"yenin imâmları, emr-i ma’rûfu ve nehy-i münkeri terk edici olsalardı, kitâblarında bunları yazarlar mı ve bu derece mübâlega ederler mi idi? Abdülkâdir-i Geylânî hazretleri buyuruyor ki: Kur’ân-ı kerîme ve hadîs-i şerîflere ve akla uygun şeylere (Ma’rûf), bunlara uymıyan şeylere (Münker) denir.","s":90},
  {"t":"Münâfık","c":"Müslimân olmıyan, fekat, müslimân görünen kâfire (Münâfık) denir.","s":1051},
  {"t":"Mürekkeb cism","c":"Birbirine benzemiyen atomların yığınına, bileşik cism veyâ (Mürekkeb cism) denir.","s":547},
  {"t":"Mürekkeb veyâ bileşik cism","c":"İki veyâ dahâ çok eleman, birbirleri ile birleşerek, başka sıfatları taşıyan, yeni bir madde meydâna getirilebilir ki, bu yeni maddeye (Mürekkeb veyâ bileşik cism) denir.","s":971},
  {"t":"Mürted","c":"Müslimânlıkdan ayrılıp, kâfir olana (Mürted) denir.","s":1051},
  {"t":"Mürâhık","c":"Oniki ve dokuz yaşlarını doldurup da, bâlig olmamış çocuğa (Mürâhık) denir.","s":227},
  {"t":"Mürşid","c":"İnsanları müslimân ve sâlih yapmak için uğraşan velîye (Mürşid) denir.","s":78},
  {"t":"Müselles","c":"Üzüm suyu, tâze iken, ya’nî gaz kabarcıkları çıkmadan, köpürmeden önce, ısıtılıp, üçde ikisi uçar, üçde biri kalırsa (Müselles) denir.","s":625},
  {"t":"Müslimân","c":"Îmân edip de ibâdet edene, ya’nî bu dört farzı yapana (Müslim) veyâ (Müslimân) denir.","s":18},
  {"t":"Müslimân olmak","c":"Allahü teâlânın var olduğuna, bir olduğuna ve Muhammed aleyhisselâmın Onun Peygamberi olduğuna ve Peygamberlerinin en üstünü olduğuna ve bunun her sözünün doğru, fâideli olduğuna inanmağa (Îmân etmek) ve (Müslimân olmak) denir.","s":1043},
  {"t":"Müsta’mel su","c":"Abdestde, guslde kullanılan suya (Müsta’mel su) denir.","s":155},
  {"t":"Müste’min kâfir","c":"SİGORTA: İbni Âbidîn “rahmetullahi aleyh”, (Redd-ül-muhtâr) kitâbında, kâfirin emân ile, ya’nî izn verilerek islâm memleketine gelmesini anlatırken diyor ki, başka bir memlekete, onların izni ile giren kâfire (Müste’min kâfir) denir.","s":874},
  {"t":"Müşrik","c":"Böyle inanmağa (Şirk) ve inanan kimseye (Müşrik) denir.","s":452},
  {"t":"Mü’min","c":"Böylece inanan insanlara, (Mü’min) denir.","s":17},
  {"t":"Nafaka","c":"Bunlara, (Nafaka) denir.","s":618},
  {"t":"Nasîhat","c":"Dil ile yapmağa (Va’z) ve (Nasîhat) denir.","s":885},
  {"t":"Natürel","c":"Maddenin yaratılmasına yarayan sebebler arasında insan gücü bulunmazsa, böyle yaratılan maddeye (Tabî’î cism) veyâ (Natürel) denir.","s":433},
  {"t":"Nebî","c":"Resûllere tâbi’ olan bu Peygamberlere de, (Nebî) denir.","s":18},
  {"t":"Nebîz","c":"Soğuyunca süzülür. Bu sıvıya, (Nebîz) denir.","s":625},
  {"t":"Necdî","c":"Üçüncüsü, sünnîlere ve şî’îlere düşman olanlardır. Bunlara (Vehhâbî) ve (Necdî) denir.","s":401},
  {"t":"Necâşî","c":"711 — NECÂŞÎ “rahmetullahi teâlâ aleyh”: Habeş pâdişâhlarının hepsine (Necâşî) denir.","s":1154},
  {"t":"Nefs-i nâtıka","c":"Buna, (Nefs-i nâtıka) denir.","s":754},
  {"t":"Niyyet etdim, yarın oruc tutmağa","c":"] Fecr, ya’nî imsâk vaktinden evvel niyyet ederken, (Niyyet etdim, yarın oruc tutmağa) denir.","s":315},
  {"t":"Ni’met","c":"İnsânların, sıhhatli, sağlam ve râhat, neş’eli yaşamalarına ve âhıretde sonsuz se’âdete kavuşmalarına sebeb olan fâideli şeylere (Ni’met) denir.","s":1048},
  {"t":"Nokta-i cevvâle","c":"Bir dâire üzerinde dönen bu küçük cisme (Nokta-i cevvâle) denir.","s":930},
  {"t":"Nukûd","c":"(Nakd), külçe veyâ meskûk, ya’nî basılmış para hâlindeki altın ve gümüşlere (Nakd), (Nakdeyn) ve (Nukûd) denir.","s":793},
  {"t":"Nâfile ibâdet","c":"Edâ veyâ kazâ etdikden sonra, kendiliğinden tekrâr yapmağa (Nâfile ibâdet) denir.","s":52},
  {"t":"Nükleon","c":"Proton ile nötronların ikisine de, (Nükleon) denir.","s":560},
  {"t":"Nükleon kuvvetleri","c":"Çekirdeklerde sıkışmış olan protonlar hep müsbet (pozitif) elektrikli olduğundan, birbirlerini itip, çekirdeğin dağılması lâzım iken, çekirdeklerin dağılmamasına sebeb, protonlar arasındaki mu’azzam bir câzibe kuvvetidir. Buna (Nükleon kuvvetleri) denir.","s":560},
  {"t":"Nüsük","c":"Menâsikden herbirine (Nüsük) denir.","s":339},
  {"t":"Nısf-ün-nehâr dâiresi = Meridiyen","c":"Nısf-ün-nehâr düzleminin, semâ küresini kesdiği dâireye, o mahallin (Nısf-ün-nehâr dâiresi = Meridiyen) denir.","s":177},
  {"t":"Nısf-ün-nehâr hattı","c":"Üfk-ı hakîkî sathını kesdiği doğruya, o mahallin (Nısf-ün-nehâr hattı) denir.","s":177},
  {"t":"Olay","c":"Cismlerde meydâna gelen değişikliğe (Hâdise) veyâ (Olay) denir.","s":1041},
  {"t":"Orta Avrupa zemânı","c":"Şarkda yedibuçuk derecedeki tûl dâiresi ile yirmi iki buçuk dereceden geçen tûl dâiresi arasında kullanılan müşterek vasatî sâat, Londra sâatinden bir sâat ileridir. Buna (Orta Avrupa zemânı) denir.","s":190},
  {"t":"Pil","c":"İçerisinde, uygun bir şeklde yerleşdirilmiş, nâzım madde ile uranium bulunan âlete (Pil) denir.","s":556},
  {"t":"Plasma","c":"Kan suyuna (Plasma) denir.","s":977},
  {"t":"Poliçe","c":"Borcu, belli bir zemân sonra, kendine veyâ adı yazılı başka bir kimseye ödemesi için, alacaklının, borcluya gönderdiği mektûba, (Poliçe) denir.","s":833},
  {"t":"Proton","c":"Hidrogen atomunun çekirdeği, artık bölünemiyen mini mini bir dânecikdir. Bu hidrogen çekirdeğine, (Proton) denir.","s":560},
  {"t":"Put","c":"Böyle inanmağa (Şirk) ve inanan kimseye (Müşrik) denir. Bu şeylere (Şerîk), (Ma’bûd), (Put) denir.","s":452},
  {"t":"Putperest","c":"Kendisinde ülûhiyyet sıfatı bulunduğuna inandıkları bir insanın heykeli, mezârı karşısında secde ederek, onun herşeyi yapacağına inananlara (Müşrik) veyâ (Putperest) denir.","s":1043},
  {"t":"Rahîm-ilhamdü","c":"[Ya’nî (Rahîm-ilhamdü) denir.","s":993},
  {"t":"Ravd-ül-enf","c":"Süheylî şerhine (Ravd-ül-enf) denir.","s":1114},
  {"t":"Ravda-i mutahhera","c":"Ravda-i mubâreke nasıl olur da, dahâ üstün olur? [Medîne câmi’i içinde, Resûlullahın “sallallahü aleyhi ve sellem” kabr-i şerîfi ile câmi’in o zemânki minberi arasındaki, yirmialtı metre uzunluğundaki yere (Ravda-i mutahhera) denir.","s":267},
  {"t":"Reaksiyon, tepkime","c":"Maddelerin birbirine te’sîr etmesine (Reaksiyon, tepkime) denir.","s":971},
  {"t":"Red olunmıyanlar","c":"Fekat, zevc ile zevceye geri verilmez. Bu ikisine, (Red olunmıyanlar) denir.","s":1031},
  {"t":"Reddiyye mes’eleleri","c":"İkinci kısm problemlere, (Reddiyye mes’eleleri) denir.","s":1031},
  {"t":"Regâib gecesi","c":"Ya’nî sapık olur. 8 — RECEB AYI VE REGÂİB GECESİ: Receb ayının ilk Cum’a gecesine (Regâib gecesi) denir.","s":355},
  {"t":"Resûl","c":"Allahü teâlâ, Âdem aleyhisselâmdan beri, her bin senede, bir Peygamber vâsıtası ile, insanlara bir din göndermişdir. Bu Peygamberlere “salevâtullahi teâlâ aleyhim ecma’în” (Resûl) denir.","s":18},
  {"t":"Revâkıyyûn","c":"995 — ZENON: Eski yunan felesofudur. Bunun felsefesine (Revâkıyyûn) denir.","s":1195},
  {"t":"Râbıta","c":"Böyle, kalb ile görmeğe (Râbıta) denir ki, kalbi, Allahü teâlâdan başka şeyleri sevmekden, onları düşünmekden kurtaran vâsıtadır.","s":904},
  {"t":"Râsıd","c":"Semâya bakan insana (Râsıd) denir.","s":175},
  {"t":"Rükn","c":"Her şeyin vücûdü, ya’nî var olması, bir işin yapılmasına bağlıdır. Bu bağlılık, beş dürlü olur: İş, bu şeyin mâhiyyetinin içinde ise, onun bir parçası ise, bu işe, (Rükn) denir.","s":122},
  {"t":"Rükn-i hacer-il esved","c":"dâda karşı olana (Rükn-i ırâkî), Yemen cihetinde olana (Rükn-i yemânî), dördüncü köşeye de (Rükn-i hacer-il esved) denir.","s":348},
  {"t":"Rıdâ’","c":"37 — SÜT KARDEŞLİK (Nikâye) kitâbının fârisî şerhinde buyuruyor ki, memeden süt emmeğe, (Rıdâ’) denir.","s":586},
  {"t":"Sadaka verirken isrâf etmeyin","c":"Allahü teâlâ, isrâf edenleri elbette sevmez) buyuruldu. Bu da, (Sadaka verirken isrâf etmeyin) demekdir.","s":644},
  {"t":"Saf madde","c":"Yalnız bir maddeye (Saf madde) denir.","s":546},
  {"t":"Sahâbî","c":"Resûlullahın “sallallahü aleyhi ve sellem” o güzel nûrlu yüzünü gören kimseye, (Sahâbî) denir.","s":1046},
  {"t":"Sahîh temizlik","c":"Âdet zemânından sonra başlıyan onbeş veyâ dahâ ziyâde gün içinde hiç kan görülmezse ve öncesi ve sonrası hayz günleri olursa, bu temiz günlere (Sahîh temizlik) denir.","s":136},
  {"t":"Sahîhayn","c":"İçinde yedibinikiyüzyetmişbeş [7275] hadîs vardır. Bu iki kitâba (Sahîhayn) denir.","s":1153},
  {"t":"Sanem","c":"Tahtâvî, (İmdâd) şerhinde diyor ki, (Odundan, altından, gümüşden yapılmış insan heykeline, (Sanem) denir.","s":628},
  {"t":"Sapma açısı","c":"Bir şehrde pusula doğrultusu ile hakîkî kutub doğrultusu arasındaki zâviyeye (Sapma açısı) denir.","s":171},
  {"t":"Sathî üfuk","c":"Bu beş düzlem, birbirlerine paraleldir. 6– Râsıdın ayaklarından geçen üfk-ı hissî düzlemine (Sathî üfuk) denir.","s":175},
  {"t":"Sathî üfuk hattı","c":"Râsıdın gözünden çıkan şu’â istikâmetine, ya’nî MS doğrusuna (Sathî üfuk hattı) denir.","s":180},
  {"t":"Savme’a","c":"Hıristiyanların ma’bedine (Kilise) ve (Bî’a) veyâ (Savme’a) denir.","s":244},
  {"t":"Sebeb","c":"Te’sîr etmiyorsa, işin yapılması, bu şeyin vücûdünü îcâb ediyorsa, (Sebeb) denir.","s":122},
  {"t":"Seker","c":"Hurmanın nakî’i, ya’nî maserasyonu, ya’nî su içinde ısıtmadan bırakılınca, köpüklenir ve tadı keskin olursa (Seker) denir, damlası harâmdır.","s":624},
  {"t":"Selef-i sâlihîn","c":"[Eshâb-ı kirâm ile Tâbi’în-i ızâma (Selef-i sâlihîn) denir.","s":768},
  {"t":"Selefiyye","c":"Ehl-i sünnet olmayıp, Ehl-i sünnet âlimlerinin (Nass)larda açık bildirilmemiş olan ahkâmdaki ictihâdlarını beğenmeyen ve bu ma’nâsı açıkca anlaşılamıyan nassları yanlış te’vîl ederek, anladıklarını Selef-i sâlihînin yolu olarak savunan sapıklara (Silfiyye) veyâ (Selefiyye) denir.","s":408},
  {"t":"Semt düzlemleri","c":"Bir mahallin şâkûlünden geçen düzlemlere (Semt düzlemleri) denir.","s":177},
  {"t":"Semâ kutbu","c":"Erd mihverinin [ekseninin] semâ küresini kesdiği iki noktaya (Semâ kutbu) denir.","s":177},
  {"t":"Semâ küresi","c":"Güneşin ve yıldızların üzerinde hareket etdikleri zan olunan küreye (Semâ küresi) denir.","s":175},
  {"t":"Seni boşadım","c":"Ya’nî, (Seni tatlîk etdim) veyâ (Seni boşadım) denir.","s":581},
  {"t":"Seretân","c":"Yengeç denilen hayvana ve kanser denilen tehlükeli şişlere arabîde (Seretân) denir.","s":626},
  {"t":"Serum","c":"Pıhtı üstündeki berrâk sıvıya (Serum) denir.","s":977},
  {"t":"Sevâb","c":"Va’d etdiği iyiliklerin ölçü birimine, (Ecr) ve (Sevâb) denir.","s":681},
  {"t":"Seyyid","c":"İmâm-ı Hasen evlâdına (Şerîf), imâm-ı Hüseyn evlâdlarına (Seyyid) denir.","s":377},
  {"t":"Sitâre","c":"O sene Mısrdan gönderilen, üzerinde kırmızı ipekle Yasîn sûresi yazılı beyâz ipek perde, Şebeke etrâfına asıldı. Bu perdeye (Sitâre) denir.","s":350},
  {"t":"Spektroskopi","c":"Bir şuâ’lanmada meydâna gelen dalgaların boylarını aramağa, (Spektroskopi) denir.","s":548},
  {"t":"Sun’î ilkâh","c":"Sun’î İlkâh: (El-halâl vel-harâm)da diyor ki, (Erkeğin menîsini, bir tüp veyâ başka şey içinde, nikâhlı zevcesi olmıyan yabancı bir kadının rahmine koyup, çocuk hâsıl olmasına, (Sun’î ilkâh) denir.","s":605},
  {"t":"Sâbikûn","c":"Akl-ı selîm sâhibi olan, bu mes’ûd insanlara (Sâbikûn) denir.","s":530},
  {"t":"Sâdık","c":"Başkalarının da kavuşmalarına vâsıta olana (Vesîle) ve (Mürşid), bunların üçüne de (Sâdık) denir.","s":1051},
  {"t":"Sâf cism","c":"Bir maddeden yapılmış cismlere, (Sâf cism) denir.","s":971},
  {"t":"Sâhib","c":"Vekîl edene (Sâhib) denir.","s":834},
  {"t":"Sâlih","c":"Allahü teâlânın sevgisine kavuşmak için çalışana (Sâlih) denir.","s":1051},
  {"t":"Sâlik","c":"İslâmiyyetin sûretini elde eden, ya’nî vilâyet-i âmmeye, Allahü teâlânın sevgisine kavuşanlar, tarîkatda, ya’nî tesavvuf yolunda ilerliyerek, vilâyet-i hâssaya kavuşabilirler. Bu yolda ilerliyen müslimâna (Sâlik) denir.","s":949},
  {"t":"Sâ’î","c":"Bunların zekâtlarını, halîfenin me’mûrları gelip toplar. Bu me’mûrlara (Sâ’î) denir.","s":309},
  {"t":"Sözleşmede veyâ sonradan ayn olan","c":"Ya’nî yukarıdaki ta’rîfde bulunan (Ayn) kelimesi, (Sözleşmede veyâ sonradan ayn olan) demekdir.","s":851},
  {"t":"Sübhâne rabbiyel-a’lâ","c":"Secdede en az üç kerre (Sübhâne rabbiyel-a’lâ) denir.","s":217},
  {"t":"Sünnet","c":"Allahü teâlânın, açıkca bildirmeyip, yalnız Peygamberimizin “sallallahü aleyhi ve sellem” yapılmasını övdüğü, yâhud devâm üzere yapdığı, yâhud yapılırken görüp de mâni’ olmadığı şeylere (Sünnet) denir.","s":18},
  {"t":"Sünnet-i gayr-ı müekkede","c":"Kendisi ara sıra terk etmiş ise, (Sünnet-i gayr-ı müekkede) denir.","s":52},
  {"t":"Sünnet-i zevâid","c":"Resûlullahın “sallallahü aleyhi ve sellem” ibâdet olarak değil de, âdet olarak, devâmlı yapdığı şeylere (Sünnet-i zevâid) denir.","s":52},
  {"t":"Sünnî","c":"Dört mezhebden birinin îmân ve fıkh bilgilerine tâbi’ olan [uyan] bir müslimâna (Ehl-i sünnet) veyâ (Sünnî) denir.","s":445},
  {"t":"Sıfât-ı hakîkiyye","c":"Bunlar, hayât [diri olmak], ilm [bilmek], sem’ [işitmek], basar [görmek], kudret [gücü yetmek], irâde [istemek], kelâm [söylemek] ve tekvîn [yaratmak]dır. Bu sekiz sıfata, (Sıfât-ı sübûtiyye) ve (Sıfât-ı hakîkiyye) denir.","s":103},
  {"t":"Tabî’at","c":"Maddelerin, cismlerin ve maddelerde bulunan enerjilerin hepsine (Âlem) veyâ (Tabî’at) denir.","s":1041},
  {"t":"Tahkîm","c":"Buna, (Tahkîm) denir.","s":884},
  {"t":"Tahrîmen mekrûh","c":"68 — NEMÂZIN MEKRÛHLARI Aşağıdaki bilgilerin çoğu, (Dürr-ül-muhtâr)dan ve bunun şerhi olan (Redd-ülmuhtâr)dan terceme edilmişdir: Nemâzın mekrûhları iki dürlüdür: Yalnız mekrûh denildiği zemân (Tahrîmen mekrûh) demekdir ki, delîlinden zan ile anlaşılan yasaklardır.","s":236},
  {"t":"Takdîr","c":"(Dürr-i yektâ) şerhinin sâhibi “rahmetullahi teâlâ aleyh” diyor ki, (İnsanların kalbleri ile veyâ bedenleri ile yapdıkları her işin ve canlılarda ve cansız şeylerde meydâna gelen her işin, Allahü teâlânın ezelde bilmesi ve dilemesi ve halk etmesi ile olmalarına (Kader) ve (Takdîr) denir.","s":702},
  {"t":"Takvîm-i Celâlî","c":"[471] hicrî senesinde, güneş takvîmi yapdırdı. Buna (Takvîm-i Celâlî) denir.","s":1134},
  {"t":"Talâk-ı bâin","c":"Boşanmak için konulmuş olan kelimeleri erkeğin zevcesine karşı söylemesi ile talâk hâsıl olur. Bu kelimelerden birini söyler söylemez hâsıl olan ayırmağa (Talâk-ı bâin) denir.","s":580},
  {"t":"Talâk-ı ric’î","c":"İddet zemânı geçdikden sonra hâsıl olan talâka, (Talâk-ı ric’î) denir.","s":580},
  {"t":"Tam râbıta","c":"Üçüncü kısma (Tam râbıta) denirdi.","s":922},
  {"t":"Tam temizlik","c":"Sahîh temizliğe ve hükmî temizliğe (Tam temizlik) denir.","s":136},
  {"t":"Tasvîr","c":"Kumaşa, dıvâra ve başka yerlere yapılmış cânlı ve cânsız resmlerine, (Sûret) veyâ (Tasvîr) denir.","s":628},
  {"t":"Tayf analizi=spektral analiz","c":"Herhangi bir madde tarafından yayılan şuâ’lanmanın spektroskopisini yaparak, bu maddede hangi elementlerin bulunduğunu aramağa (Tayf analizi=spektral analiz) denir.","s":548},
  {"t":"Ta’dîl-i zemân","c":"Hakîkî ve vasatî gün uzunlukları aynı iken, sonraki günlerde hâsıl olan farklara (Ta’dîl-i zemân) denir.","s":189},
  {"t":"Ta’vîz","c":"Âyet-i kerîme ile ve Resûlullahdan gelen düâlar ile Rukye yapmağa, (Ta’vîz) denir.","s":783},
  {"t":"Tebe’ı tâbi’în","c":"Tâbi’înden sonra, insanların en üstünleri, Tâbi’îni gören ve onların sohbetinde yetişen müslimânlardır. Bunlara (Tebe’ı tâbi’în) denir.","s":495},
  {"t":"Tebzîr","c":"Malı, islâmiyyetin ve mürüvvetin uygun görmediği yerlere dağıtmağa (İsrâf) veyâ (Tebzîr) denir.","s":640},
  {"t":"Tefekkür","c":"Ni’metleri de düşünülürse, buna (Tefekkür) denir.","s":903},
  {"t":"Tefsîr","c":"Resûlullahın “sallallahü aleyhi ve sellem” bildirdiği ma’nâlara (Tefsîr) denir.","s":9},
  {"t":"Telfîk","c":"Dört mezhebin kolay taraflarını araşdırıp, birbirine karışdırmağa (Telfîk) denir.","s":470},
  {"t":"Telfîk-ı mezâhib","c":"Dört mezhebin kolaylıklarını araşdırıp, bunları bir araya toplayarak, yeni bir kolaylıklar mezhebi uydurmağa (Telfîk-ı mezâhib) denir.","s":468},
  {"t":"Temkin","c":"Güneşin merkezinin hakîkî üfukdan gurûbundan sonra, arka kenârının, bu gurûb vaktinden, bu irtifâ’ zâviyesi kadar, dahâ aşağıya, ya’nî üfk-ı şer’îye inerek, ziyânın en yüksek tepeden gayb olması için geçen zemâna (Temkin) denir.","s":186},
  {"t":"Temîme","c":"Bunu veyâ nazarlık denilen şeyleri kendi üzerinde taşımağa, (Temîme) denir.","s":784},
  {"t":"Tenvîr dâiresi","c":"Hasîb beğ, (Kozmografya) kitâbında diyor ki: (Güneşden, birbirine müvâzî [paralel] olarak gelen şuâ’lardan, Erd küresine temâs ederek geçenlerin, bu temâs noktaları, büyük bir dâire hâsıl eder. Bu dâireye (Tenvîr dâiresi) denir.","s":183},
  {"t":"Tenzîhen mekrûh","c":"Yasak olmasına bir delîl, sened bulunmayıp, yapılmaması iyi olan şeye (Tenzîhen mekrûh) denir.","s":236},
  {"t":"Tesavvuf","c":"Bunlar, Resûlullahın mubârek kalbinden çıkıp, Evliyânın kalblerine gelen bilgilerdir. Bu bilgilere (Tesavvuf) denir.","s":1043},
  {"t":"Teselsül","c":"Böylece, kadîm olmıyan yaratıcılar zinciri mevcûd olur. Bu zincire, (Teselsül) denir.","s":760},
  {"t":"Tevbe etmek","c":"[Bu üzülmeğe ve karâra (Tevbe etmek) denir.","s":64},
  {"t":"Tevhîdde şerî’at","c":"] Süâl — İnsanın elinde birşey yoksa, niçin sevâb ve azâb oluyor ve niçin dinler, şerî’atler gönderiliyor? Cevâb — Bu süâle (Şerî’atde tevhîd) ve (Tevhîdde şerî’at) denir ki, burada çok kimseler boğulmuşdur.","s":680},
  {"t":"Tevâcüd","c":"İrâdî ve ihtiyârî olarak raks etmeğe, (Tevâcüd) denir.","s":721},
  {"t":"Te’vîl","c":"[Bir kelimenin, Allahü teâlâ ve Resûlullah tarafından, açık bildirilmemiş ma’nâlarından, islâmiyyete uygun olanı seçmeğe (Te’vîl) denir.","s":771},
  {"t":"Timsâl","c":"Yalnız cânlı resmlerine, (Timsâl) denir.","s":628},
  {"t":"Titreşimli akımın frekansı","c":"Sâniyedeki gidip gelme sayısına (Titreşimli akımın frekansı) denir.","s":986},
  {"t":"Tivele","c":"Muhabbet hâsıl etmek için yapılan rukyelere, (Tivele) denir.","s":784},
  {"t":"Todesstrahlen","c":"Harblerde kullanılabileceklerinden, bunlara ölüm şuâ’ları (Todesstrahlen) denir.","s":974},
  {"t":"Tokmaktepe","c":"Bu da orada medfûndur. Bunun için oradaki kabristâna (Tokmaktepe) denir.","s":1103},
  {"t":"Tuğra","c":"Osmânlı pâdişâhlarının mührlerine, (Tuğra) denir.","s":621},
  {"t":"Tâbi’în","c":"Birkaç dânesine (Eshâb) denir. O güzeli göremeyip de, yalnız, Sahâbîyi görenlere (Tâbi’în) denir.","s":1046},
  {"t":"Tâm şehîd","c":"müslimânların ve ehl-i zimmetin cânlarını, mallarını korumak için olan çarpışma yerinde bulunan ölü üzerinde yara, kan akması gibi öldürülme alâmetleri görülürse veyâ şehrde öldürülmüş bulunup, kâtili bilinir ve kısâs yapılması lâzım gelirse, bunlara (Dünyâ ve âhıret şehîdi) ve (Tâm şehîd) denir.","s":998},
  {"t":"Türkistân","c":"Yârkend, Fergâne ve Kâşgar buradadır. Bu memleketlerin hepsine (Türkistân) denir.","s":431},
  {"t":"Tılâ","c":"Tâze şıra, ateşde veyâ güneşde ısıtılıp üçde ikisinden azı uçarsa, [üçde birinden çok kalırsa], bu kalana, (Tılâ) denir.","s":624},
  {"t":"Ukûbât","c":"(Dürr-ül-muhtâr) üçüncü cüz’de buyuruyor ki: Döğerek, kolu keserek, recm ederek, ya’nî öldürünceye kadar taş atarak veyâ öldürerek yapılan cezâlara (Ukûbât) denir.","s":879},
  {"t":"Ulûm-i hikemiyye","c":"Canlıları öğretene (Ulûm-i tıbbiyye), cansızları öğretene (Ulûm-i hikemiyye) denir.","s":25},
  {"t":"Ulûm-i islâmiyye","c":"ih ilmli, hakîkî din âlimi, seyyid Abdülhakîm Efendinin “rahmetullahi aleyh” bir mektûba cevâbı olup, tefsîri ve hadîs-i şerîfleri bildirmekde, din âlimlerini medh eylemekdedir: Efendim, Kıymetli mektûbunuzun başında, din âlimlerinin, müslimânların öğrenmesi lâzım olan bilgilere (Ulûm-i islâmiyye) denir, dediklerini yazıyorsunuz.","s":413},
  {"t":"Ulûm-i nakliyye","c":"Böyle bilgilere, (Ulûm-i nakliyye) denir.","s":543},
  {"t":"Urûz","c":"Hayvândan başka, menkûl olan kıyemî mallara, (Urûz) denir.","s":793},
  {"t":"Uşr","c":"Toprakdan alınan mahsûlün zekâtına (Uşr) denir.","s":303},
  {"t":"Vasatî gün","c":"Hakîkî zevâl vaktinde, zemânları ölçen, meselâ kol sâatimiz, 12 de iken başlıyarak, ertesi gün 12 ye kadar geçen tam 24 sâatlik zemâna bir (Vasatî gün) denir.","s":188},
  {"t":"Vatan","c":"İnsanın mukîm olduğu, yerleşdiği yere (Vatan) denir.","s":224},
  {"t":"Ve aleyküm","c":"Onlar selâm verince, yalnız (Ve aleyküm) denir.","s":364},
  {"t":"Vecd","c":"İhtiyârî olmıyan raksa (Vecd) denir.","s":721},
  {"t":"Vehhâbîlik","c":") Sapık din adamı Ahmed ibni Teymiyyenin kitâblarındaki bozuk fikrleri ile ingiliz câsûsu Hempherin yalanlarının ve iftirâlarının karışımına (Vehhâbîlik) denir.","s":482},
  {"t":"Vekîl","c":"Yerine geçirilen başka kimseye (Vekîl) denir.","s":834},
  {"t":"Velî","c":"Allahü teâlânın sevgisine kavuşmak için çalışana (Sâlih) denir. Bu sevgiye kavuşmuş olana (Ârif) veyâ (Velî) denir.","s":1051},
  {"t":"Vera’","c":"[İbni Âbidîn, imâmlığın şartlarında buyuruyor ki, (Şübhelilerden sakınmağa, ya’nî şübhelilerden ittikâya (Vera’) denir.","s":96},
  {"t":"Vesen","c":"Taşdan yapılan insan heykeline, (Vesen) denir.","s":628},
  {"t":"Vesîle","c":"Kendisine izn verilen zâta (Halîfe) veyâ (Vesîle) denir.","s":768},
  {"t":"Vâcib","c":"İnanması farz olmayıp, vâcib olan, yapması farz olan emrlere (Vâcib) denir.","s":230},
  {"t":"Yahyâ","c":"3- (Yuhannâ) olup, (Yahyâ) demekdir.","s":1108},
  {"t":"Ya’kûbiyye","c":"Fikrlerine (Monofisiyye) veyâ (Ya’kûbiyye) denir.","s":1089},
  {"t":"Yobaz","c":"İster Ehl-i sünnet olsun, ister bid’at sâhibi olsun, dînini dünyâ çıkarlarına âlet eden, ya’nî dünyâlığa kavuşmak için dîninden veren câhillere (Yobaz) denir.","s":473},
  {"t":"Yıldız günü","c":"Bir yıldızın, bulunulan mahallin Nısf-ün-nehârından iki geçişi arasındaki zemâna bir (Yıldız günü) denir.","s":183},
  {"t":"Zarûret","c":"İkinci kısmda, otuzsekizinci maddeye bakınız! İnsanı birşey yapmağa zorlıyan semâvî sebebe, ya’nî insanın elinde olmıyarak hâsıl olan sebebe (Zarûret) denir.","s":135},
  {"t":"Za’îm","c":"Kirâ almak hakkı bulunan askere (Timarcı), subaylara (Za’îm) denirdi.","s":305},
  {"t":"Zikr-i cehrî","c":"Başkası da işitirse (Zikr-i cehrî) denir.","s":903},
  {"t":"Zikr-i hafî","c":"Dil ile kendi işitecek kadar söylenirse, islâmiyyetde (Zikr-i hafî) denir.","s":903},
  {"t":"Zimmî","c":"Bunlar, islâmın kuvveti ve büyüklüğü karşısında, küçüklüklerini anlamış, cizye vermeği kabûl ederek islâmın hâkimiyyetine ve adâletine sığınmışdır. Bu kâfirlere (Ehl-i zimmet) veyâ (Zimmî) denir.","s":39},
  {"t":"Zâhirî gurûb","c":"İkinci gurûb, arka kenârın, râsıdın bulunduğu mahallin zâhirî üfuk hattına nazaran zâhirî irtifâ’ının sıfır olduğu, ya’nî bu üst kenârının, mahallin üfk-ı zâhirî hattından gayb olduğunun görüldüğü vaktdir. Buna (Zâhirî gurûb) denir.","s":186},
  {"t":"Zâhirî irtifâ’ kavsi","c":"Güneşin bir Z kenârından geçen semt dâiresinin, bu kenârı kesdiği nokta ile, hissî, mer’î, riyâdî ve hakîkî üfuk düzlemlerini kesdiği, semâdaki iki nokta arasındaki kavslerine, bu üfuklara nazaran (Zâhirî irtifâ’ kavsi) denir.","s":177},
  {"t":"Zühd","c":"Şübheli olmak korkusu ile mubâhların çoğunu terk etmeğe de (Zühd) denir).","s":96},
  {"t":"Züyûf","c":"Altını, gümüşü yarıdan fazla olan nukûddan; altını, gümüşü en çok olanına (Ceyyid), dahâ az olanlarına (Züyûf) denir.","s":793},
  {"t":"Zındık","c":"Hiçbir dinde olmayıp da, dinsiz düşüncelerini müslimânlık imiş gibi, fâsid, bozuk delîller ile isbâta kalkışarak, müslimânların îmânlarını bozmak istiyene (Zındık) denir).","s":463},
  {"t":"artık","c":"ARTIKLAR: Bir kabdan veyâ küçük havuzdan, bir canlı içerse, kalan suya (artık) denir.","s":162},
  {"t":"aynı yer","c":"İzotop, yunanca (aynı yer) demekdir.","s":554},
  {"t":"azîm","c":"İbni Âbidîn üçyüzotuzikinci sahîfede diyor ki, (Rükü’ tesbîhinde (Zı) ile (azîm) denir ki, Rabbim büyükdür demekdir.","s":724},
  {"t":"bid’at ehli","c":"Peygamberimiz, (İbâdetleri benden ve eshâbımdan gördüğünüz gibi yapınız! İbâdetlerde değişiklik yapanlara (bid’at ehli) denir.","s":169},
  {"t":"bugün oruc tutmağa","c":"İmsâkdan sonra niyyet ederken, (bugün oruc tutmağa) denir.","s":315},
  {"t":"büyük havuz","c":"Eni on zrâ’ [4,8 metre], boyu da on zrâ’ olan kare şeklindeki havuza (büyük havuz) denir ki, sathı [alanı] yüz zrâ’ kare, ya’nî yirmiüç metre karedir.","s":161},
  {"t":"ekran","c":"Kutunun kapağının iç yüzü parlak bir levhadır. Bu levhaya (ekran) denir.","s":563},
  {"t":"gülüyor","c":"İshak, (gülüyor) demekdir.","s":1122},
  {"t":"hafî okumak","c":"Kendi kulakları işitecek kadar sesli okumağa, (hafî okumak) denir.","s":216},
  {"t":"ihtiyâc maddeleri","c":"[Bunlara (ihtiyâc maddeleri) denir.","s":647},
  {"t":"inşikak=yarılma","c":"Uranium 235 atomunun bu sûretle parçalanmasına fission (inşikak=yarılma) denir ki, Radioaktiviteye hiç benzemiyor.","s":554},
  {"t":"için","c":"Hicr sûresinin son âyetindeki (hattâ) kelîmesi, belki de (için) demekdir.","s":952},
  {"t":"karbonhidrat","c":"Yasak olanlar - Şekerli ve nişastalı her madde yasakdır. Bunlara (karbonhidrat) denir.","s":658},
  {"t":"kıymeti","c":"Mebî’in piyasadaki fiyâtına, değeri (kıymeti) denir.","s":795},
  {"t":"menkûl","c":"Bir yere götürülmesi mümkin olan mala (menkûl) denir.","s":792},
  {"t":"müellif","c":"Bir âlim kitâb yazarsa, bu kitâba (te’lîf), yazana (müellif) denir.","s":1208},
  {"t":"perléche","c":"37 — UÇUK: Fransızca (perléche) denir.","s":674},
  {"t":"pul","c":"Bir felse, türkçede mangır, fârisîde (pul) denir.","s":796},
  {"t":"sadaka verirken, harâm olan isrâfdan sakının!","c":"Kâdî Beydâvî ve Zemahşerî ve Fahreddîn-i Râzî gibi büyük âlimlerin tefsîrlerinde ve dahâ birçok tefsîrlerde diyor ki, âyet-i kerîmede, (rızklardan) kelimesi, (rızkların ba’zısını, bir kısmını) demek olup, (sadaka verirken, harâm olan isrâfdan sakının!) demekdir.","s":644},
  {"t":"segonder=bilvâsıta, ikinci anemi","c":"Başka sebebden meydâna geldiği için buna (segonder=bilvâsıta, ikinci anemi) denir.","s":977},
  {"t":"silis-ül-bevl","c":"(Kitâbürrahme)de diyor ki, (Devâmlı idrâr kaçırmağa (silis-ül-bevl) denir.","s":128},
  {"t":"tanzîm edici","c":"Bunu başarmak için, tabî’î Uranium parçası içine, nötron yakalamıyan çekirdekli atomlardan yapılmış maddeler karışdırılıyor. Bu maddelere (modérateur) deniyor ki, nâzım (tanzîm edici) demekdir.","s":556},
  {"t":"tevbe bî’ati","c":"Buna, (tevbe bî’ati) denir.","s":766},
  {"t":"ve salli ve sellim ve bârik aleyhi ve aleyhim kesîran kesîrâ.","c":"Üç def’a okunur ve üçüncüsünde (ve salli ve sellim ve bârik aleyhi ve aleyhim kesîran kesîrâ.) denir.","s":243},
  {"t":"yankı","c":"Geri dönen dalgalar, eşit özellikde, ikinci bir ses meydâna getirirler. Bu ikinci sese (Aks-i sadâ) veyâ (yankı) denir.","s":725},
  {"t":"yıldız sâati","c":"Bir yıldızın, bulunulan mahallin Nısf-ün-nehârından iki geçişi arasındaki zemâna bir (Yıldız günü) denir. Bu zemânın 24 de birine bir (yıldız sâati) denir.","s":183},
  {"t":"Âdet zemânı","c":"Hayz kanı görüldüğü andan, kesildiği güne kadar olan günlerin sayısına (Âdet zemânı) denir.","s":136},
  {"t":"Âdetde bid’at","c":"Böyle, Allahü teâlâya ibâdet etmek ve sevâb kazanmak niyyeti olmaksızın meydâna çıkarılan şeylere, (Âdetde bid’at) denir.","s":631},
  {"t":"Âdil","c":"Büyük günâh işlemiyen ve küçük günâha devâm etmeyen ve hasenesi seyyiesinden çok olan müslimâna (Âdil) denir.","s":884},
  {"t":"Âhıret hayâtı","c":"Kıyâmetden önceki zemân, kıyâmetden sonraki zemândan dahâ yakın olduğu için, birincisine (Dünyâ hayâtı), ikincisine (Âhıret hayâtı) denir.","s":78},
  {"t":"Âlem","c":"(Nebrâs) ve bunun Berhurdâr “rahmetullahi teâlâ aleyh” hâşiyesinde diyor ki: Mahlûkların hepsine (Âlem) denir.","s":758},
  {"t":"Âlem-i sagîr","c":"İnsana, (Âlem-i sagîr) denir.","s":86},
  {"t":"Ârif","c":"Allahü teâlâya yakın olmak, Onun sevmesine kavuşmak demekdir. Bu se’âdete kavuşana (Velî) ve (Ârif) denir.","s":1057},
  {"t":"Âşir","c":"(Âmil), hem (Sâ’î), hem de (Âşir) demekdir.","s":308},
  {"t":"Îcâb","c":"Alıcı ve satıcıdan, râzı olduğunu hangisi önce söylerse, buna (Îcâb) denir.","s":792},
  {"t":"Îmân","c":"Resûlullahın “sallallahü aleyhi ve sellem” söylediklerinin hepsini beğenip kalbin kabûl etmesine, ya’nî inanmasına (Îmân) denir.","s":17},
  {"t":"Îmân-ı şühûdî","c":"Aynadır demek Evliyâlığa uygundur ve buna (Îmân-ı şühûdî) denir.","s":931},
  {"t":"Ölüm hastası","c":"(Redd-ül-muhtâr) dördüncü cildde buyuruyor ki, (İhtiyâclarını te’mîn etmek için sokağa çıkamıyan hastaya, (Ölüm hastası) denir.","s":816},
  {"t":"Üfk düzlemleri","c":"ME hattı râsıdın şâkûlüdür. Bu şâkûle dik olan düzlemlere râsıdın (Üfk düzlemleri) denir.","s":175},
  {"t":"Üfk-ı zâhirî hattı","c":"Etrâfımıza bakınca yer ile gök, büyük bir dâirenin kavsi üzerinde birleşmiş gibi görünüyor. Bu dâireye (Üfk-ı zâhirî hattı) denir.","s":175},
  {"t":"Ülûhiyyet sıfatları","c":"[Allahü teâlâya mahsûs olan sıfatlara, (Sıfât-i zâtiyye)ye ve (Sıfât-i sübûtiyye)ye (Ülûhiyyet sıfatları) denir.","s":452},
  {"t":"Üveysî","c":"Rûhların terbiye etdiği kimseye (Üveysî) denir.","s":1189},
  {"t":"Ü’îzü-kümâ","c":"İki kişiye okurken (Ü’îzü-kümâ) denir.","s":785},
  {"t":"Ü’îzüke","c":"Bir kimseye okurken, E’ûzü yerine (Ü’îzüke) denir.","s":785},
  {"t":"çıkık","c":"Buna, (çıkık) denir.","s":675},
  {"t":"örtülü","c":"Cin, cinnet, cinân, Cennet, cenân ve cenîn gibi C ve N harflerinden meydâna gelen kelimeler (örtülü) demekdir.","s":735},
  {"t":"İbrâhîm “aleyhisselâm”, Âzer olan babasına dediği zemân","c":"Îcâz, belâgat ve fesâhat kâ’idelerine göre, âyet-i kerîmenin ma’nâsı (İbrâhîm “aleyhisselâm”, Âzer olan babasına dediği zemân) demekdir.","s":389},
  {"t":"İbâdet etmek","c":"İhlâs ile, ya’nî Allahü teâlânın rızâsına, sevgisine kavuşmak ve sevâb kazanmak niyyeti ile, farzları, sünnetleri yapmağa ve harâmlardan ve mekrûhlardan kaçınmağa, ya’nî ahkâm-ı islâmiyyeyi yerine getirmeğe (İbâdet etmek) denir.","s":20},
  {"t":"İbâdethâne","c":"CÂMİ’DE YAPILMASI CÂİZ OLMIYAN ŞEYLER YİRMİİKİDİR: İbâdet yapmak için, toplanılan yerlere (Ma’bed) veyâ (İbâdethâne) denir.","s":244},
  {"t":"İcmâ’-ı ümmet","c":"Selef-i sâlihînin söz birliğine (İcmâ’-ı ümmet) denir.","s":437},
  {"t":"İctihâd","c":"Bu benzetmeyi yapabilecek derin âlimlere (Müctehid) denir. Bu benzetmek işine, (İctihâd) denir.","s":464},
  {"t":"İctimâ’ı neyyireyn=Conjunction","c":"Her devrinde, bir kerre, ay ile güneş, yer küresinin aynı tarafında olarak, üçü bir doğrultuda bulunuyorlar. Bu hâle (İctimâ’ı neyyireyn=Conjunction) denir.","s":360},
  {"t":"İhtikâr","c":"Bir şehre dışardan gelen gıdâ ve ihtiyâc eşyâsını, şehr hâricinde karşılayarak ucuz alıp, şehrde depo ederek pahâlı satmak harâmdır. Buna (İhtikâr) denir.","s":813},
  {"t":"İhtiyât zemânı","c":"İmsâkin iki vakti arasındaki [On dakîka kadar] zemâna (İhtiyât zemânı) denir.","s":316},
  {"t":"İkinci nev’","c":"Kur’ân-ı kerîmde açıkca emr edilmiş olan, yukarıda, ikinci numarada yazılı, altı farzdan, nısf, rubu’, sümün cinslerine (Birinci nev’), sülüsân, sülüs ve südüs cinslerine (İkinci nev’) denir.","s":1030},
  {"t":"İkinci sınıf bileşikler","c":"İçinde üç element bulunan anorganik bileşiklere, (İkinci sınıf bileşikler) denir.","s":547},
  {"t":"İllet","c":"Dışında ise, bu şeye te’sîr ediyorsa, (İllet) denir.","s":122},
  {"t":"İlm-i ferâiz","c":"64 — FERÂİZ BİLGİSİ Vefât eden kimsenin bırakdığı malın kimlere verileceğini ve nasıl dağıtılacağını öğreten ilme, (İlm-i ferâiz) denir.","s":1025},
  {"t":"İlm-i fıkh","c":"Beden ile yapılacak ahkâm-ı islâmiyyeyi bildiren ilme (İlm-i fıkh) denir.","s":103},
  {"t":"İlm-i kelâm","c":"Bunları anlatan geniş ve derin ilme (İlm-i kelâm) denir.","s":103},
  {"t":"İlm-ül-yakîn","c":"(Müceddidiyye) büyükleri, [ya’nî, imâm-ı Rabbânî talebelerinden tâ bu zemâna kadar gelenler] buyurdular ki, murâkabe ve zikr ederken, keyfiyyetlerin, hâllerin ve nûrların hâsıl olmasına (İlm-ül-yakîn) denir.","s":765},
  {"t":"İnhitât-ı üfuk zâviyesi","c":"Sathî üfka nazaran olan ZS irtifâ’ından hakîkî irtifâ’dan ZN in farkına, M yüksekliği için (İnhitât-ı üfuk zâviyesi) denir.","s":181},
  {"t":"İnternet","c":"Ara merkezlerde bulunan bilgisayar, ya’nî (computer)lerin bir uydu vâsıtası ile, semâya gönderdikleri elektro-manyetik dalgaların fezâdaki topluluğuna (İnternet) denir.","s":563},
  {"t":"İrtifâ’ dâireleri","c":"Semt düzlemlerinin semâ küresini kesdiklerini düşünürsek, küre sathında hâsıl etdikleri bu dâirelere, o mahallin (Semt dâiresi=Azimut)leri veyâ (İrtifâ’ dâireleri) denir.","s":177},
  {"t":"İrtifâ’ zâviyesi","c":"ye çıkarılınca, bir derece 29 dakîka 6,2 sâniye olur ki, buna güneşin (İrtifâ’ zâviyesi) denir.","s":186},
  {"t":"İslâm bilgileri","c":"Fâideli ilm, se’âdet-i ebediyyeyi elde etmeğe, ya’nî Allahü teâlânın rızâsını kazanmaya vesîle olan ilmdir ki, bunlara, (İslâm bilgileri) denir).","s":260},
  {"t":"İslâm âlimi","c":"Mal, mevkı’ ve şöhret için olmamasıdır. Bu üçüne sâhib olan müslimâna (Hakîkî müslimân) ve (İslâm âlimi) denir.","s":16},
  {"t":"İslâmiyyet","c":"Peygamberleri “aleyhimüssalevâtü vetteslîmât” ile gönderdiği bu emr ve yasakların toplamına, (İlâhî din)ler veyâ (İslâmiyyet) denir.","s":529},
  {"t":"İsmâ’îlî","c":"Yedinci imâm İsmâ’îldir ve ondan sonra çocuklarıdır diyen sapıklara (İsmâ’îlî) denir.","s":1084},
  {"t":"İstidlâlî","c":"Düşünmekle bilinirse, (İstidlâlî) denir.","s":782},
  {"t":"İstidrâc","c":"3 — Ümmet arasında, Velî olmıyanlardan meydâna gelen âdet dışı şeylere, (Fi - râset) denir. 4 — Fâsıklardan, günâhı çok olanlardan zuhûr ederse (İstidrâc) denir ki, derece derece, kıymetini indirmek demekdir.","s":748},
  {"t":"İstigfâr etmek","c":"Günâhlarını afv etmesi için Allahü teâlâya yalvarmağa (İstigfâr etmek) denir.","s":64},
  {"t":"İstinşâk","c":"4 — Burnu, ayrı ayrı su ile, üç kerre yıkamak. Buna (İstinşâk) denir.","s":122},
  {"t":"İyon","c":"Elektrik yükü taşıyan atomlara (İyon) denir.","s":547},
  {"t":"İyon şebekesi","c":"Bunlara, (İyon şebekesi) denir.","s":547},
  {"t":"İâde","c":"Bir nemâzı vakti içinde tekrâr kılmağa (İâde) denir.","s":272},
  {"t":"İşrâkıyyun","c":"757 — PİSAGOR: Eski yunan filosofudur. Bunun felsefesine (İşrâkıyyun) denir.","s":1161},
  {"t":"Şart","c":"Îcâb etmiyorsa, işin yapılmaması ile, o şey de yok olursa, (Şart) denir.","s":122},
  {"t":"Şebeke-i se’âdet","c":"Beşyüzelli senesinde, Cemâleddîn-i İsfehânî, ikinci dıvar etrâfına sandal ağacından parmaklık yapdı. Bu parmaklığa (Şebeke-i se’âdet) denir.","s":350},
  {"t":"Şefî’","c":"950 — Başkasına satılmış olan bir mülkü, satış değeri ile satınalmak hakkına (Şüf’a) denir. Bu hakka mâlik olan kimseye, (Şefî’) denir.","s":536},
  {"t":"Şehvet","c":"Biri, muhtâc oldukları, lezzet aldıkları şeyleri istemek, onlara kavuşmak kuvvetidir. Bu kuvvete, (Şehvet) denir.","s":529},
  {"t":"Şer","c":"Fâide hâsıl olanlara (Hayr), zarar hâsıl olanlara (Şer) denir.","s":697},
  {"t":"Şerîf","c":"Soyundan olanlara (Şerîf) denir.","s":1107},
  {"t":"Şerîf-i Ca’ferî","c":"Zeyneb, Abdüllah bin Ca’fer Tayyâr ile nikâhlanıp, Alî ve Ümm-i Gülsüm ve zürriyyetleri oldu. Bunlara (Şerîf-i Ca’ferî) denir.","s":1100},
  {"t":"Şer’î gurûb","c":"Üçüncü gurûb, arka kenârın, şer’î üfka nazaran irtifâ’ının sıfır olduğu hesâb olunan vaktdir. Buna (Şer’î gurûb) denir.","s":186},
  {"t":"Şer’î irtifâ’","c":"Güneşin kenârının, şer’î üfka göre olan irtifâ’ına (Şer’î irtifâ’) denir.","s":181},
  {"t":"Şer’î zevâl mahalli","c":"Râsıd, bulunduğu mahallin en yüksek yerine çıkınca, semâdaki (zevâl mahalli dâiresi), en dışarda ve en büyük olur. Bu en büyük zevâl mahalli dâiresine Râsıdın (Şer’î zevâl mahalli) denir.","s":181},
  {"t":"Şeyh-ul-hadîs","c":"İkiyüzbin hadîs-i şerîfi ezbere bilene (Şeyh-ul-hadîs) denir.","s":423},
  {"t":"Şirk","c":"Böyle inanmağa (Şirk) denir.","s":570},
  {"t":"Şâhid","c":")] ŞÂHİDLİK: (Tercemet-ül-muhtasar) adındaki (Nikâye)nin fârisî şerhınde di - yor ki: Birinin başkasında bulunan hakkını haber verene (Şâhid) denir.","s":884},
  {"t":"Şâkûlü","c":"Râsıdın ayaklarından geçen Erdın yarı çapı istikâmetine râsıdın (Şâkûlü) denir.","s":175},
  {"t":"Şî’î","c":"(Hadîka)da, ikinci kısmın sonunda buyuruyor ki, (Hazret-i Alîyi üç halîfeden üstün tutana (Şî’î) denir.","s":408},
  {"t":"Şüf’a","c":"Devletin parası yetişmezse, istifâde edenlerden toplanır. 950 — Başkasına satılmış olan bir mülkü, satış değeri ile satınalmak hakkına (Şüf’a) denir.","s":536},
  {"t":"şer’î üfk hattı","c":"4– Erdin merkezinden geçen (Hakîkî üfk) düzlemi. 5– Râsıdın bulunduğu yerin en yüksek noktasının zâhirî üfk hattından geçen P (Şer’î üfk) düzlemidir ki, bu düzlemin yer küresini kesdiği q dâireye (şer’î üfk hattı) denir.","s":175},
  {"t":"şu kadar para ile","c":"Vekîle, âdet olan yol ve nafaka masrafı hesâblanarak (şu kadar para ile) denir.","s":341}
];